### ISSUE TITLE
double records in rec_table using get_rec

### ISSUE THREAD

**Issue by jimcasaer** [inbo/camtraptor#100]
when applying the following lines on the current export of the GMU8 project in Agouti - double records appear in the rec_table
a possible reason could be that two observations for one sequence result in two records in the record table ? 

first lines of record table below the script lines -- doubles in records 1&2, 4&5, 6&7

unzip("./Grofwild/Meerdaal/Data/Input/Agouti/gmu8.zip",exdir = "./filesGMU8")
GMU8 <- camtraptor::read_camtrap_dp("./filesGMU8")

start_date <- lubridate::as_datetime("2018-01-01")
end_date <- lubridate::as_datetime("2018-08-31")

rec_table_2018 <- get_record_table(GMU8, pred_and(pred_gte("start", start_date), pred_lte("end", end_date)),
  stationCol = "locationName",
  exclude = NULL,
  minDeltaTime = 0,
  deltaTimeComparedTo = NULL
)

1
2018_1_1304
Aix galericulata
2018-04-06 21:52:42
2018-04-06
21:52:42
0
0.000000
0.00000000
0.000000000
c("https://multimedia.agouti.eu/assets/9c2f5f8a-c021-47ef-a768-b109c1d9226b/file", "https://multimedia.agouti.eu/assets/ac26fae4-5ec1-48fe-84fc-6ce6a91019f6/file", "https://multimedia.agouti.eu/assets/55cecdca-fe21-4a6b-a9de-c4d4c40f4e51/file", "https://multimedia.agouti.eu/assets/1805f6f1-e23f-434a-bfd6-b8f9ae9c930b/file", "https://multimedia.agouti.eu/assets/b3523210-e6c6-4f1c-bb32-cd03e595a96f/file", "https://multimedia.agouti.eu/assets/64352818-35e8-450a-85ad-eea4ed0268d3/file", "https://multimedia.agouti.eu/assets/494df0c1-35eb-455c-b25c-768420c1a5a6/file",  "https://multimedia.agouti.eu/assets/7d767837-2939-4939-b59d-ea268b63b324/file", "https://multimedia.agouti.eu/assets/d51691e6-31a2-4e7a-9102-42e1611305c6/file", "https://multimedia.agouti.eu/assets/1cf97a67-8db9-4867-8d5c-79e922c28b6b/file")
c("20180601110735-IMG_0264.JPG", "20180601110735-IMG_0265.JPG", "20180601110739-IMG_0266.JPG", "20180601110739-IMG_0267.JPG", "20180601110739-IMG_0268.JPG", "20180601110739-IMG_0269.JPG", "20180601110739-IMG_0270.JPG", "20180601110743-IMG_0271.JPG", "20180601110743-IMG_0272.JPG", "20180601110743-IMG_0273.JPG")
2
2018_1_1304
Aix galericulata
2018-04-06 21:52:42
2018-04-06
21:52:42
0
0.000000
0.00000000
0.000000000
c("https://multimedia.agouti.eu/assets/9c2f5f8a-c021-47ef-a768-b109c1d9226b/file", "https://multimedia.agouti.eu/assets/ac26fae4-5ec1-48fe-84fc-6ce6a91019f6/file", "https://multimedia.agouti.eu/assets/55cecdca-fe21-4a6b-a9de-c4d4c40f4e51/file", "https://multimedia.agouti.eu/assets/1805f6f1-e23f-434a-bfd6-b8f9ae9c930b/file", "https://multimedia.agouti.eu/assets/b3523210-e6c6-4f1c-bb32-cd03e595a96f/file", "https://multimedia.agouti.eu/assets/64352818-35e8-450a-85ad-eea4ed0268d3/file", "https://multimedia.agouti.eu/assets/494df0c1-35eb-455c-b25c-768420c1a5a6/file",  "https://multimedia.agouti.eu/assets/7d767837-2939-4939-b59d-ea268b63b324/file", "https://multimedia.agouti.eu/assets/d51691e6-31a2-4e7a-9102-42e1611305c6/file", "https://multimedia.agouti.eu/assets/1cf97a67-8db9-4867-8d5c-79e922c28b6b/file")
c("20180601110735-IMG_0264.JPG", "20180601110735-IMG_0265.JPG", "20180601110739-IMG_0266.JPG", "20180601110739-IMG_0267.JPG", "20180601110739-IMG_0268.JPG", "20180601110739-IMG_0269.JPG", "20180601110739-IMG_0270.JPG", "20180601110743-IMG_0271.JPG", "20180601110743-IMG_0272.JPG", "20180601110743-IMG_0273.JPG")
3
2018_1_1549
Anas platyrhynchos
2018-03-30 08:39:39
2018-03-30
08:39:39
0
0.000000
0.00000000
0.000000000
c("https://multimedia.agouti.eu/assets/d8f1761f-1295-481b-a8af-aca036a6438d/file", "https://multimedia.agouti.eu/assets/cfef13d0-4b54-4d24-9ca5-0f34c3c6e49b/file", "https://multimedia.agouti.eu/assets/76bfeeeb-a96c-409d-97dd-6d290ad4ea94/file", "https://multimedia.agouti.eu/assets/0128e513-85af-4323-8a47-120d422135f6/file", "https://multimedia.agouti.eu/assets/7641a9ca-65b6-4a5b-9dd5-e771ecca79b2/file", "https://multimedia.agouti.eu/assets/43280d73-6b78-4ac4-949c-0471001ffc5c/file", "https://multimedia.agouti.eu/assets/f5a46e08-c9d4-44ba-b928-195c869f2cfc/file",  "https://multimedia.agouti.eu/assets/7df0f1e6-3200-4a7c-840c-640d757fc2b5/file", "https://multimedia.agouti.eu/assets/f2e5e0ab-d183-4152-8052-655f6244b1cc/file", "https://multimedia.agouti.eu/assets/45f2640b-a0d8-4441-97ee-323776fc0504/file")
c("20180601092900-IMG_0449.JPG", "20180601092900-IMG_0450.JPG", "20180601092900-IMG_0451.JPG", "20180601092900-IMG_0452.JPG", "20180601092900-IMG_0453.JPG", "20180601092900-IMG_0454.JPG", "20180601092900-IMG_0455.JPG", "20180601092900-IMG_0456.JPG", "20180601092900-IMG_0457.JPG", "20180601092900-IMG_0458.JPG")
4
2018_1_557
Anas platyrhynchos
2018-03-31 11:26:08
2018-03-31
11:26:08
0
0.000000
0.00000000
0.000000000
c("https://multimedia.agouti.eu/assets/4651e8c2-c226-483a-9b6f-2dea09701852/file", "https://multimedia.agouti.eu/assets/784677e9-6724-412b-994e-47d33908bb46/file", "https://multimedia.agouti.eu/assets/2e4e943c-a47e-40eb-9004-cd9b3d896f1b/file", "https://multimedia.agouti.eu/assets/a77fc723-2241-461e-9980-3bdc07f42550/file", "https://multimedia.agouti.eu/assets/8917857a-5aa4-4d68-81da-1ee4cf89b3a2/file", "https://multimedia.agouti.eu/assets/8466c709-8db5-4e85-9243-3b4dc878063e/file", "https://multimedia.agouti.eu/assets/38a4089f-ee39-4ed6-800a-cfc67c598d5e/file",  "https://multimedia.agouti.eu/assets/11a6745f-e9a0-4a17-85e2-ee828144ac17/file", "https://multimedia.agouti.eu/assets/b9be17c2-99ea-41f5-9cc4-9ee6f7a20788/file", "https://multimedia.agouti.eu/assets/0713f440-f56c-4228-a6da-c451c738bb4b/file", "https://multimedia.agouti.eu/assets/7ab0ae49-3495-4af3-9680-d0485507cfed/file", "https://multimedia.agouti.eu/assets/92166665-1c48-4459-a405-2bb1c3f00970/file", "https://multimedia.agouti.eu/assets/b647fa8c-e5a5-463a-b844-412d91db2036/file", "https://multimedia.agouti.eu/assets/52d607bc-8416-4773-854f-8901c2914d31/file",  "https://multimedia.agouti.eu/assets/80f5468e-449c-4319-8ac4-115b9d0cdb5f/file", "https://multimedia.agouti.eu/assets/c8eb1585-152d-4d9f-8170-7ebabf6c57b0/file", "https://multimedia.agouti.eu/assets/f3ca8f2c-3f31-48b1-a4dd-badfe80fe16d/file", "https://multimedia.agouti.eu/assets/a40bb37d-98fb-447c-aa49-ad438832109c/file", "https://multimedia.agouti.eu/assets/8168b1ab-dff3-4e34-a66c-03b8f44a5a46/file", "https://multimedia.agouti.eu/assets/1ecb579e-2c28-49a0-be86-c0fa3289774f/file")
c("20180601120851-IMG_0113.JPG", "20180601120851-IMG_0114.JPG", "20180601120851-IMG_0115.JPG", "20180601120854-IMG_0116.JPG", "20180601120854-IMG_0117.JPG", "20180601120854-IMG_0118.JPG", "20180601120854-IMG_0119.JPG", "20180601120854-IMG_0120.JPG", "20180601120858-IMG_0121.JPG", "20180601120858-IMG_0122.JPG", "20180601120858-IMG_0123.JPG", "20180601120858-IMG_0124.JPG", "20180601120858-IMG_0125.JPG", "20180601120902-IMG_0126.JPG", "20180601120902-IMG_0127.JPG", "20180601120902-IMG_0128.JPG", "20180601120902-IMG_0129.JPG",  "20180601120902-IMG_0130.JPG", "20180601120905-IMG_0131.JPG", "20180601120905-IMG_0132.JPG")
5
2018_1_557
Anas platyrhynchos
2018-03-31 11:26:08
2018-03-31
11:26:08
0
0.000000
0.00000000
0.000000000
c("https://multimedia.agouti.eu/assets/4651e8c2-c226-483a-9b6f-2dea09701852/file", "https://multimedia.agouti.eu/assets/784677e9-6724-412b-994e-47d33908bb46/file", "https://multimedia.agouti.eu/assets/2e4e943c-a47e-40eb-9004-cd9b3d896f1b/file", "https://multimedia.agouti.eu/assets/a77fc723-2241-461e-9980-3bdc07f42550/file", "https://multimedia.agouti.eu/assets/8917857a-5aa4-4d68-81da-1ee4cf89b3a2/file", "https://multimedia.agouti.eu/assets/8466c709-8db5-4e85-9243-3b4dc878063e/file", "https://multimedia.agouti.eu/assets/38a4089f-ee39-4ed6-800a-cfc67c598d5e/file",  "https://multimedia.agouti.eu/assets/11a6745f-e9a0-4a17-85e2-ee828144ac17/file", "https://multimedia.agouti.eu/assets/b9be17c2-99ea-41f5-9cc4-9ee6f7a20788/file", "https://multimedia.agouti.eu/assets/0713f440-f56c-4228-a6da-c451c738bb4b/file", "https://multimedia.agouti.eu/assets/7ab0ae49-3495-4af3-9680-d0485507cfed/file", "https://multimedia.agouti.eu/assets/92166665-1c48-4459-a405-2bb1c3f00970/file", "https://multimedia.agouti.eu/assets/b647fa8c-e5a5-463a-b844-412d91db2036/file", "https://multimedia.agouti.eu/assets/52d607bc-8416-4773-854f-8901c2914d31/file",  "https://multimedia.agouti.eu/assets/80f5468e-449c-4319-8ac4-115b9d0cdb5f/file", "https://multimedia.agouti.eu/assets/c8eb1585-152d-4d9f-8170-7ebabf6c57b0/file", "https://multimedia.agouti.eu/assets/f3ca8f2c-3f31-48b1-a4dd-badfe80fe16d/file", "https://multimedia.agouti.eu/assets/a40bb37d-98fb-447c-aa49-ad438832109c/file", "https://multimedia.agouti.eu/assets/8168b1ab-dff3-4e34-a66c-03b8f44a5a46/file", "https://multimedia.agouti.eu/assets/1ecb579e-2c28-49a0-be86-c0fa3289774f/file")
c("20180601120851-IMG_0113.JPG", "20180601120851-IMG_0114.JPG", "20180601120851-IMG_0115.JPG", "20180601120854-IMG_0116.JPG", "20180601120854-IMG_0117.JPG", "20180601120854-IMG_0118.JPG", "20180601120854-IMG_0119.JPG", "20180601120854-IMG_0120.JPG", "20180601120858-IMG_0121.JPG", "20180601120858-IMG_0122.JPG", "20180601120858-IMG_0123.JPG", "20180601120858-IMG_0124.JPG", "20180601120858-IMG_0125.JPG", "20180601120902-IMG_0126.JPG", "20180601120902-IMG_0127.JPG", "20180601120902-IMG_0128.JPG", "20180601120902-IMG_0129.JPG",  "20180601120902-IMG_0130.JPG", "20180601120905-IMG_0131.JPG", "20180601120905-IMG_0132.JPG")
6
2018_1_557
Anas platyrhynchos
2018-04-03 12:40:23
2018-04-03
12:40:23
263655
4394.250000
73.23750000
3.051562500
c("https://multimedia.agouti.eu/assets/0056f12e-fa57-4474-850d-3c9796214e46/file", "https://multimedia.agouti.eu/assets/dd49a5e0-81d0-4013-b226-dd050068078b/file", "https://multimedia.agouti.eu/assets/5364c53d-58b1-4056-99ea-32e19b1cd55e/file", "https://multimedia.agouti.eu/assets/5190f8bf-b4f9-433b-b242-480f57e853b4/file", "https://multimedia.agouti.eu/assets/c17b2ffd-01bd-42e4-969a-52b55331c0f3/file", "https://multimedia.agouti.eu/assets/3cc6ac57-53d0-4aba-a281-426d4ec31c99/file", "https://multimedia.agouti.eu/assets/e694a235-b374-4d26-a3d1-21e0af60e836/file",  "https://multimedia.agouti.eu/assets/13515290-df03-4074-8a06-ba98eb0cc724/file", "https://multimedia.agouti.eu/assets/3d2199c2-19bb-4d2a-aa7a-16a773a984a0/file", "https://multimedia.agouti.eu/assets/54c229b4-8617-4f90-8fd1-650ffb4ea81b/file")
c("20180601120923-IMG_0159.JPG", "20180601120923-IMG_0160.JPG", "20180601120927-IMG_0161.JPG", "20180601120927-IMG_0162.JPG", "20180601120927-IMG_0163.JPG", "20180601120927-IMG_0164.JPG", "20180601120927-IMG_0165.JPG", "20180601120931-IMG_0166.JPG", "20180601120930-IMG_0167.JPG", "20180601120930-IMG_0168.JPG")
7
2018_1_557
Anas platyrhynchos
2018-04-03 12:40:23
2018-04-03
12:40:23

**Comment by damianooldoni** [comment]
Thanks @jimcasaer to share your findings. I will give a look. Could you please share the wip file with me? Thanks.

**Comment by damianooldoni** [comment]
@jimcasaer: still without the raw data you are going to send me, I can already say that you are right while guessing the reason of the duplicates. The function `get_record_table()` starts from slot `observations`, not from slot `media` to assess the record table. So, if two observations are linked to the same sequence, a duplicate will arise. 
In documentation of [`camtrapR::recordTable()`](https://jniedballa.github.io/camtrapR/reference/recordTable.html) I can see that there is an argument called `removeDuplicateRecords` (logical) described as follows:
> If there are several records of the same species at the same station (also same camera if cameraID is defined) at exactly the same time, show only one?

And I see that the default value is `TRUE`. I will add this option to our function as well with same defeault behavior.

**Comment by jimcasaer** [comment]
I sent you a zip-file -- can you confirm ?

**Comment by damianooldoni** [comment]
yes, downloaded. I am working on this issue right now. Soon a new version of camtraptor with this issue (hopefully) solved 👍

**Comment by damianooldoni** [comment]
PR #102 is written. Waiting for the result of the automatic tests. This evening I will merge the PR if everything is ok. I tested the new feature with the datapackage you sent me (GMU8) and indeed, the record table produced with your code has 400 rows less than the same code with argument `removeDuplicateRecords = FALSE`. 
Without duplicates: 1473 rows
With duplicates: 1873 rows

**Comment by damianooldoni** [comment]
No, definitely not a _mierenneuken_ 😄 Indeed, important to explain it correctly. I will do it in a new small PR.
