### ISSUE TITLE
Add `predict.pos` function

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtraptor#103]
Predicts position relative to camera given image pixel positions and site calibration models. This function is used by Agouti (but it should use it from this R package, rather than copy/pasting source code). 

Written by @MarcusRowcliffe in https://github.com/MarcusRowcliffe/CTtracking/blob/9601a79e2e66a4d0e6a831aeeb632e132f1d2c45/CTtracking.r#L949-L971

**Comment by damianooldoni** [comment]
Some notes for @MarcusRowcliffe and @peterdesmet:

## Functions

1. camtraptor use snake_case convention. I would rename `predict.pos()` as `predict_pos()`.
2. `predict.pos()` uses another function called `predict.r` ([L929-L942](https://github.com/MarcusRowcliffe/CTtracking/blob/9601a79e2e66a4d0e6a831aeeb632e132f1d2c45/CTtracking.r#L929-L942)). I will add it as well and I would like to add it as `predict_r()` (as explained in 1).
3. `predict.r` seems to be a small help function, i.e. it can be hidden, not exposed to the users of the package and so put in `zzz.R` where all help functions are stored.

## Arguments

1. As for function, I would like to maintain snake_case convention. This means that I would rename the argument `deptag` as `dep_tag`.
2. I would add two extra arguments to allow users to pass the strings naming the columns within `dat` containing `x` and `y` values. Default: `"x"` and `"y"`. This not only adds flexibility to the function but it makes the function args more consequent as the function has already an arg, `deptag`, for indicating the column to use (see [L956-L958](https://github.com/MarcusRowcliffe/CTtracking/blob/9601a79e2e66a4d0e6a831aeeb632e132f1d2c45/CTtracking.r#L956-L958))

## Tests

1. Does somebody already have some basic data to use in unit tests for both the functions? Just to know.

**Comment by damianooldoni** [comment]
This has been done.
