### ISSUE TITLE
Move the metadata in datapackage up to root level

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtraptor#113]
Currently, the object returned by:

```R
dp <- read_camtrap_dp("inst/extdata/mica/datapackage.json")
```

Is a list with 4 elements:

- dp$observations
- dp$deployments
- dp$media
- dp$datapackage

By nesting all the metadata to a lower level, the resulting `dp` is different from what would be returned by `frictionles::read_package()`. I would make the objects compatible, by moving the metadata up to the root level. We just have to make sure that the added elements (observations, deployments, media) don't conflict with current names (they don't) or by grouping the data in a `data` object (also no name conflict).

I other words:

```
 $ name         : chr "mica-muskrat-and-coypu-20210707160815"
 $ id           : chr "https://doi.org/10.5281/zenodo.4893244"
 $ profile      : chr "https://raw.githubusercontent.com/tdwg/camtrap-dp/0.1.6/camtrap-dp-profile.json"
 $ created      : chr "2021-07-07T16:08:15Z"
 $ sources      :List of 1
 ...
 $ deployments
 $ media
 $ observations
```

Or grouped:

```
 $ name         : chr "mica-muskrat-and-coypu-20210707160815"
 $ id           : chr "https://doi.org/10.5281/zenodo.4893244"
 $ profile      : chr "https://raw.githubusercontent.com/tdwg/camtrap-dp/0.1.6/camtrap-dp-profile.json"
 $ created      : chr "2021-07-07T16:08:15Z"
 $ sources      :List of 1
 ...
 $ data
 ..$ deployments
 ..$ media
 ..$ observations
```

**Comment by damianooldoni** [comment]
Thanks for reminder about the hotfix, @peterdesmet. I start to tackle this issue.
As we discussed two days ago, we go for grouping resources in slot `data`. This will avoid possible duplicates with metadata slots and makes also easy for the user to search the right resource within the package as typically we have very few resources and a lot of metadata slots.
