### ISSUE TITLE
Update `write_dwc()` so it works from non-published datasets

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtraptor#132]
I.e. not requiring a DOI.

**Comment by peterdesmet** [comment]
Current implementation:

```R
write_dwc <- function(
  package,
  directory = ".",
  doi = package$id,
  contact = NULL,
  rights_holder = package$rightsHolder
) {
```

Suggestion:

```R
write_dwc <- function(
  package,
  directory = ".",
  eml = TRUE,
  contact = NULL,
  rights_holder = package$rightsHolder
) {
```

When `eml=TRUE`, the function will attempt to create an `eml.xml`. This could be based on:

- Metadata of an already published dataset. It needs a DOI for that, which can be provided in `metadata.id` of the package. @damianooldoni do you think that is sufficient for the user or should this be more clearly communicated by retaining `doi` as a function parameter?
- Metadata it find in the package. It might not be sufficient to create a valid `eml.xml`, but it can do a best attempt.

In the data, some Darwin Core terms are also derived from the metadata:

- license: dataset.license > metadata.license > NULL
- rightsHolder: param `rightsHolder` > metadata.rightsHolder > NULL
- datasetID: dataset.doi > metadata.id > NULL
- collectionCode: metadata.platform > NULL
- datasetName: dataset.title > metadata.title > NULL

**Comment by peterdesmet** [comment]
Combinations with two parameters:

- eml=FALSE, doi=NULL: no `eml.xml`, 5 fields in DwC are attempted to be populated from package
- eml=FALSE, doi="...": no `eml.xml`, 5 fields in DwC are set from dataset at DOI
- eml=TRUE, doi=NULL: `eml.xml` and 5 fields in DwC are set based on package info
- eml=TRUE, doi="...":  `eml.xml` and 5 fields in DwC are set based on dataset at DOI

**Comment by peterdesmet** [comment]
Alternatively, we could split in `write_dwc()` and `write_eml()`.

**Comment by damianooldoni** [comment]
> Metadata of an already published dataset. It needs a DOI for that, which can be provided in metadata.id of the package. @damianooldoni do you think that is sufficient for the user or should this be more clearly communicated by retaining doi as a function parameter?

I think so, as long as it is documented in the Roxygen and is part of a vignette (see #118). And I think it's a very clean approach: if a DOI is assigned, then it's good practice to mention it in the metadata of the package, isn't?

> Alternatively, we could split in write_dwc() and write_eml()

I think it's always nice to split functions in subfunctions anytime the scopes are well defined.
