### ISSUE TITLE
Error message for `check_value()`

### ISSUE THREAD

**Issue by Rafnuss** [inbo/camtraptor#154]
The error message for and invalid package is 
```
> get_n_obs(dp)
Error: Invalid value for species argument.
Valid inputs are: dendroperdix sephaena, genetta maculata, tychaedon quadrivirgata, hystrix cristata, rhynchocyon chrysopygus, nesotragus moschatus, potamochoerus larvatus, mellivora capensis, tragelaphus scriptus, petrodromus tetradactylus, homo sapiens, caracal caracal, guttera edouardi, papio cynocephalus, homo sapiens, helogale parvula, cephalophus harveyi, ichneumia albicauda, capra aegagrus hircus, bos taurus and others...
```

I find it quite hard to debug. Would it be possible to add the actual `arg` not present? 
For instance, I used: `print(arg[!(arg %in% options)])` in https://github.com/inbo/camtraptor/blob/main/R/zzz.R#L121. 

But I don't fully understand how the assertthat + msg_to_print with glue works. Maybe it's not easy to do?

**Comment by damianooldoni** [comment]
Thanks @Rafnuss! I understand your concern and indeed, it would be nice to return the bad names, indeed. Finding the bad ones is indeed not trivial when the datapacakge contains many species. I will try to tackle this soon.

**Comment by peterdesmet** [comment]
In addition, you shouldn't get the error anymore with fc439c4 (which filters out non animal names from the taxonomy).

**Comment by damianooldoni** [comment]
@Rafnuss: could you please accept the invitation to the package I have just sent to you? In this way I can set you as reviewer of PR #155.

**Comment by Rafnuss** [comment]
Ok, I've accepted the invitation and accepted the review. I'm quite new to this process, so let me know if I do something wrong =).

**Comment by damianooldoni** [comment]
Thanks @Rafnuss. Welcome to the camtraptor club :+1 I see you approved the changes. To do that, I suppose you reinstalled the package from the branch via `devtools::install_github("inbo/camtraptor@improve-error-message") and tested your script? If so, great.
