### ISSUE TITLE
Write orcids as https

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtraptor#160]
Update http to https in:

https://github.com/inbo/camtraptor/blob/5768940eb76a09441a4597c0b615a40c407742cd/R/write_eml.R#L184

Once https://github.com/gbif/ipt/issues/1819 is included in the next version of the IPT.

**Comment by PietrH** [comment]
Since gbif/ipt#1819 is closed, can we implement this in camtraptor?

**Comment by peterdesmet** [comment]
Yes
