### ISSUE TITLE
`rai_individuals` missing as possible feature in `map_dep()` documentation

### ISSUE THREAD

**Issue by Rafnuss** [inbo/camtraptor#165]
https://github.com/inbo/camtraptor/blob/main/R/map_dep.R#L12-L16
but
https://github.com/inbo/camtraptor/blob/main/R/map_dep.R#L324

**Comment by Rafnuss** [comment]
What's the best way to suggest a fix? New branch and new PR?

**Comment by peterdesmet** [comment]
Yes branch and PR is how we prefer it 😊

**Comment by Rafnuss** [comment]
close with #166
