### ISSUE TITLE
GBIF validation of export from `read_wi()` and `write_dwc()`

### ISSUE THREAD

**Issue by Rafnuss** [inbo/camtraptor#168]
Hey, just wanted to check with you @peterdesmet that these validation issues from the GBIF files are not something we can do at the `read_wi()` or `write_dwc()` level.

https://www.gbif.org/tools/data-validator/5547190a-10d5-4667-af3d-dc00be586117
https://www.gbif.org/tools/data-validator/47d69d10-0142-45c5-b997-ffed38be6ef5 (doesn't seem to work for audubon)

- [x] **Coordinate rounded**: Would it make sense to add `round_coordinates( , digit=6)` by default? (https://data-blog.gbif.org/post/issues-and-flags/)
- [x] **Country derived from coordinates**: ignore
- [ ] **Taxon match higherrank** and **taxon match fuzzy**: what would be the ideal way to check/modify taxonomic discrepency between WI and GBIF? Maybe not something for camtraptor, but is there a way to modify the scientific name in a datapackage? Do you recommend the use of the specie API (e.g., https://docs.ropensci.org/rgbif/reference/index.html#taxonomic-names?)

**Comment by peterdesmet** [comment]
**Coordinate rounded** means that GBIF has rounded the coordinates for us, but best practice is to provide the coordinates as they are in the source database, so I would not add a default round.

**Taxon match fuzzy**: you can verify where it goes wrong by providing a CSV of all your scientific names to https://www.gbif.org/tools/species-lookup

**Comment by peterdesmet** [comment]
Where is the `Basis of record invalid` coming from in the second link?

**Comment by Rafnuss** [comment]
> Where is the `Basis of record invalid` coming from in the second link?

The second link is the validation of the audubon file. Is this not due to the fact that the validation tool is unaware of the audubon class? (i.e., there is not validation possible for this class).

**Comment by peterdesmet** [comment]
Yes, that is definitely possible. Did you upload both files as a single DwC-Archive or separately?

**Comment by Rafnuss** [comment]
Yes, it was uploaded seperatly. Here is the one uploaded as a zip file: https://www.gbif.org/tools/data-validator/bdbd3cb4-224b-4cfc-b479-49588b64334a

**Comment by peterdesmet** [comment]
Note: here's a published (sequence level) dataset that made use of `write_eml()` and `write_dwc()`: https://www.gbif.org/dataset/8a5cbaec-2839-4471-9e1d-98df301095dd

**Comment by Rafnuss** [comment]
Do you mean this code? https://github.com/inbo/mica-occurrences/blob/master/datasets/mica-agouti-occurrences/src/dwc_mapping.Rmd
It would be nice to have that as an article (vignette) somewhere no? Useful for me at least.

**Comment by peterdesmet** [comment]
Yeah, good idea to add this as a vignette. It would have to be for the example small dataset.

**Comment by peterdesmet** [comment]
- The status of `read_wi()` is discussed in https://github.com/inbo/camtrapdp/issues/62.
- A data publication vignette is also being discussed https://github.com/inbo/camtrapdp/issues/5
- Ideally, Wildlife Insights can export as Camtrap DP in the near future, at which point a `read_wi()` is not needed
- GBIF validation is being tested with GBIF for Camtrap DPs directly.

Closing this issue, @Rafnuss let me know if there are remaining items to be tackled.
