### ISSUE TITLE
Rethinking `get_custom_effort` and `get_effort`

### ISSUE THREAD

**Issue by damianooldoni** [inbo/camtraptor#172]
While reviewing `get_*()` functions vs features of `map_dep()` (see #171) I found the function name `get_custom_effort()` very misleading.
 
@jimcasaer, @LynnINBO and I added [`get_custom_effort()`](https://inbo.github.io/camtraptor/reference/get_custom_effort.html) to allow the user to select a `start` date, an `end` date and also a `group_by` interval, e.g. "days". See #70.
Notice that such effort is calculated over **all deployments** (filtering by predicates is of course possible)!

But why not adding `start`, `end` and `group_by` to `get_effort()` as well and renaming `get_custom_effort()` as `get_total_effort()` or `get_global_effort()`?

Of course users can continue to use `get_custom_effort`, but its usage will be deprecated.

@jimcasaer, @LynnINBO, @peterdesmet: what do you think about it?

**Comment by damianooldoni** [comment]
Decided with @jimcasaer:
- yes, `start`, `end` and `group_by` fit perfectly `get_effort()`. The default values (start = NULL, end  = NULL, group_by = NULL) will return the effort as it is returned now and will be by far the most typical usage.
- agree to rename `get_custom_effort`. However,  `get_project_effort()`  of `get_overall_effort()`.

**Comment by damianooldoni** [comment]
Decided with @jimcasaer:
- yes, `start`, `end` and `group_by` fit perfectly `get_effort()`. The default values (start = NULL, end  = NULL, group_by = NULL) will return the effort as it is returned now and will be by far the most typical usage.
- agree to rename `get_custom_effort`. However, `get_global_effort()` doesn't soudn good for @jimcasaer as it reminds a calculation over the globe, the entire Earth, not anymore project wise.
- @jimcasaer's alternatives: `get_project_effort()` (I give :+1) of `get_overall_effort()` (I give :-1).

@peterdesmet:  which name is the best, do you think? Other alternatives are welcome.

**Comment by peterdesmet** [comment]
What is the difference in functionality of `get_effort(start, end, group_by)` vs `get_project_effort()`?

**Comment by damianooldoni** [comment]
get_effort is at deployment level, the actual `get_custom_effort()` (to be renamed maybe as `get_project_effort()`) is over all deployments.
Default examples:

```r
library(camtraptor)

get_effort(mica)
#> # A tibble: 4 × 4
#>   deploymentID                         effort unit  effort_duration       
#>   <chr>                                 <dbl> <chr> <Duration>            
#> 1 29b7d356-4bb4-4ec4-b792-2af5cc32efa8   239. hour  859859s (~1.42 weeks) 
#> 2 577b543a-2cf1-4b23-b6d2-cda7e2eac372   219. hour  786802s (~1.3 weeks)  
#> 3 62c200a9-0e03-4495-bcd8-032944f6f5a1   529. hour  1903602s (~3.15 weeks)
#> 4 7ca633fa-64f8-4cfc-a628-6b0c419056d7   335. hour  1204929s (~1.99 weeks)

get_custom_effort(mica)
#> # A tibble: 1 × 3
#>   begin      effort unit 
#>   <date>      <dbl> <chr>
#> 1 2019-10-09  1321. hour
Created on 2022-09-15 with reprex v2.0.2
```

**Comment by peterdesmet** [comment]
Why not a call the function `get_effort()` (`get_custom_effort()` behaviour) where you can `group_by = "deployment"` to replicate the current `get_effort()` behaviour?

**Comment by jimcasaer** [comment]
when looking at the list #171  of get_() functions, it seems to me that there are two families of get_() functions:
- those that return information for each deployment and are afterwards used in map_dep()
- the others that return information based on the export that is being analyzed 

would it not be logical to keep the get_ as a prefix for all of them and differentiate using get_dep_() for the first group and get_projet_() or get_export_() for the second ? I do not like the suggestion to use summarize (as suggested in ) given that these functions are for me not really summarizing something, but returning characteristics for each deployment

**Comment by peterdesmet** [comment]
_Suggested in camtraptor July 2023 coding sprint_

- Regarding aligning `get_custom_effort()` and `get_effort()`, see #236
- @jimcasaer agree that there are multiple families of `get_` functions:
  - Get information per deployment, like `get_effort()`
  - Get information for camtrapR, like `get_recordTable()`
  - Get species info, like `get_scientific_name()`
  We decided to remove the `get_` function names, see e.g. #231 #235 ...

Closing this issue in favour of #236
