### ISSUE TITLE
Create meta.xml for the Darwin Core export

### ISSUE THREAD

**Issue by fmendezh** [inbo/camtraptor#175]
Since the order of the fields for the data files are given by SQL queries in [https://github.com/inbo/camtraptor/tree/main/inst/sql](https://github.com/inbo/camtraptor/tree/main/inst/sql), it would make sense to generate a meta.xml file, the file would always contain the same structure, which means that it is not necessary to generate it, copy it to the directory destiny would be enough.

For the sake readability we might consider adding the occurrenceID as the first column in the occurrence file. 

I've created an example using the dwc-io java library:

```
<archive xmlns="http://rs.tdwg.org/dwc/text/">
  <core encoding="UTF-8" fieldsTerminatedBy="," linesTerminatedBy="\n" fieldsEnclosedBy="" ignoreHeaderLines="0" rowType="http://rs.tdwg.org/dwc/terms/Occurrence">
    <files>
    </files>
    <id index="8" />
    <field index="0" term="http://purl.org/dc/terms/type"/>
    <field index="1" term="http://purl.org/dc/terms/license"/>
    <field index="2" term="http://purl.org/dc/terms/rightsHolder"/>
    <field index="3" term="http://rs.tdwg.org/dwc/terms/datasetID"/>
    <field index="4" term="http://rs.tdwg.org/dwc/terms/collectionCode"/>
    <field index="5" term="http://rs.tdwg.org/dwc/terms/datasetName"/>
    <field index="6" term="http://rs.tdwg.org/dwc/terms/basisOfRecord"/>
    <field index="7" term="http://rs.tdwg.org/dwc/terms/dataGeneralizations"/>
    <field index="8" term="http://rs.tdwg.org/dwc/terms/occurrenceID"/>
    <field index="9" term="http://rs.tdwg.org/dwc/terms/individualCount"/>
    <field index="10" term="http://rs.tdwg.org/dwc/terms/sex"/>
    <field index="11" term="http://rs.tdwg.org/dwc/terms/lifeStage"/>
    <field index="12" term="http://rs.tdwg.org/dwc/terms/behavior"/>
    <field index="13" term="http://rs.tdwg.org/dwc/terms/occurrenceStatus"/>
    <field index="14" term="http://rs.tdwg.org/dwc/terms/occurrenceRemarks"/>
    <field index="15" term="http://rs.tdwg.org/dwc/terms/organismID"/>
    <field index="16" term="http://rs.tdwg.org/dwc/terms/eventID"/>
    <field index="17" term="http://rs.tdwg.org/dwc/terms/parentEventID"/>
    <field index="18" term="http://rs.tdwg.org/dwc/terms/eventDate"/>
    <field index="19" term="http://rs.tdwg.org/dwc/terms/habitat"/>
    <field index="20" term="http://rs.tdwg.org/dwc/terms/samplingProtocol"/>
    <field index="21" term="http://rs.tdwg.org/dwc/terms/samplingEffort"/>
    <field index="22" term="http://rs.tdwg.org/dwc/terms/eventRemarks"/>
    <field index="23" term="http://rs.tdwg.org/dwc/terms/locationID"/>
    <field index="24" term="http://rs.tdwg.org/dwc/terms/locality"/>
    <field index="25" term="http://rs.tdwg.org/dwc/terms/decimalLatitude"/>
    <field index="26" term="http://rs.tdwg.org/dwc/terms/decimalLongitude"/>
    <field index="27" term="http://rs.tdwg.org/dwc/terms/geodeticDatum"/>
    <field index="28" term="http://rs.tdwg.org/dwc/terms/coordinateUncertaintyInMeters"/>
    <field index="29" term="http://rs.tdwg.org/dwc/terms/coordinatePrecision"/>
    <field index="30" term="http://rs.tdwg.org/dwc/terms/identifiedBy"/>
    <field index="31" term="http://rs.tdwg.org/dwc/terms/dateIdentified"/>
    <field index="32" term="http://rs.tdwg.org/dwc/terms/identificationRemarks"/>
    <field index="33" term="http://rs.tdwg.org/dwc/terms/taxonID"/>
    <field index="34" term="http://rs.tdwg.org/dwc/terms/scientificName"/>
    <field index="35" term="http://rs.tdwg.org/dwc/terms/kingdom"/>
  </core>
  <extension encoding="UTF-8" fieldsTerminatedBy="," linesTerminatedBy="\n" fieldsEnclosedBy="" ignoreHeaderLines="0" rowType="http://rs.tdwg.org/ac/terms/Multimedia">
    <files>
    </files>
    <coreid index="0" />
    <field index="0" term="http://rs.tdwg.org/dwc/terms/occurrenceID"/>
    <field index="1" term="http://unknown.org/dcterm/rights"/>
    <field index="2" term="http://purl.org/dc/terms/identifier"/>
    <field index="3" term="http://purl.org/dc/elements/1.1/type"/>
    <field index="4" term="http://rs.tdwg.org/ac/terms/providerManagedID"/>
    <field index="5" term="http://rs.tdwg.org/ac/terms/comments"/>
    <field index="6" term="http://rs.tdwg.org/ac/terms/captureDevice"/>
    <field index="7" term="http://rs.tdwg.org/ac/terms/resourceCreationTechnique"/>
    <field index="8" term="http://rs.tdwg.org/ac/terms/accessURI"/>
    <field index="9" term="http://purl.org/dc/terms/format"/>
    <field index="10" term="http://ns.adobe.com/xap/1.0/CreateDate"/>
  </extension>
</archive>
```

**Comment by fmendezh** [comment]
@peterdesmet what term should be mapped to the column CreateDate ?

**Comment by PietrH** [comment]
To summarise: 

- [ ] hardcode `meta.xml` in `write_dwc()`
- [ ] test: read `meta.xml` and check both order and name of columns, for Occurrence and Multimedia

**Comment by PietrH** [comment]
If `directory = NULL` (return list of data.frames), should meta.xml be returned as part of the list? As an xml document? As a character vector?

**Comment by PietrH** [comment]
`providerManagedID` seems missing from the existing extension snapshot: `dwc_audubon.csv` 

[permalink](https://github.com/inbo/camtraptor/blob/339aad2fc72d0050c37c585c1ec4f9bb33403adc/tests/testthat/_snaps/write_dwc/dwc_audubon.csv)

|occurrenceID                         |dcterm:rights |identifier                           |dc:type    |comments |captureDevice |resourceCreationTechnique |accessURI                                                                     |format     |CreateDate          |
|:------------------------------------|:-------------|:------------------------------------|:----------|:--------|:-------------|:-------------------------|:-----------------------------------------------------------------------------|:----------|:-------------------|
|3d065f23-426a-449b-8693-f3c6b2ac9c7a |NA            |8263e85b-786a-4f62-9817-d54fb1dafb5d |StillImage |NA       |NA            |motion detection          |https://multimedia.agouti.eu/assets/8263e85b-786a-4f62-9817-d54fb1dafb5d/file |image/jpeg |2020-07-29 05:46:48 |
|3d065f23-426a-449b-8693-f3c6b2ac9c7a |NA            |cf97e186-9679-4cd9-95fa-dfa50d8003cc |StillImage |NA       |NA            |motion detection          |https://multimedia.agouti.eu/assets/cf97e186-9679-4cd9-95fa-dfa50d8003cc/file |image/jpeg |2020-07-29 05:46:49 |
|3d065f23-426a-449b-8693-f3c6b2ac9c7a |NA            |969ee7eb-6bd1-41b5-ac69-cd957e819f75 |StillImage |NA       |NA            |motion detection          |https://multimedia.agouti.eu/assets/969ee7eb-6bd1-41b5-ac69-cd957e819f75/file |image/jpeg |2020-07-29 05:46:49 |
|3d065f23-426a-449b-8693-f3c6b2ac9c7a |NA            |2f80c542-7c7c-490f-a34b-297029f52a9b |StillImage |NA       |NA            |motion detection          |https://multimedia.agouti.eu/assets/2f80c542-7c7c-490f-a34b-297029f52a9b/file |image/jpeg |2020-07-29 05:46:50 |
|3d065f23-426a-449b-8693-f3c6b2ac9c7a |NA            |a67541cf-0769-44ca-9af1-853298cc7580 |StillImage |NA       |NA            |motion detection          |https://multimedia.agouti.eu/assets/a67541cf-0769-44ca-9af1-853298cc7580/file |image/jpeg |2020-07-29 05:46:51 |

**Comment by peterdesmet** [comment]
Correct, `providerManagedID` was removed from the mapping, since there is no longer an originating term for it in Camtrap DP.

**Comment by PietrH** [comment]
I created a pull request #221 to implement this, I've added Damiano as a reviewer.
