### ISSUE TITLE
Add `camera_functioning` properties in `read_wi()`

### ISSUE THREAD

**Issue by Rafnuss** [inbo/camtraptor#177]
It seems like I missed to import `camera_functioning` properties from Wildlife Insight (see https://github.com/inbo/camtraptor/issues/129). 
This properties can provide useful information in the filtering of the data (e.g. before uploading on GBIF in my case)
<img width="313" alt="image" src="https://user-images.githubusercontent.com/7571260/200856870-2f50d61c-5676-4d91-82a9-63cec30c1b76.png">

**Comment by Rafnuss** [comment]
@peterdesmet , What do you think of adding this field to `deployement$comments` (https://tdwg.github.io/camtrap-dp/data/#deployments.comments) https://github.com/inbo/camtraptor/blob/HEAD/R/read_wi.R#L297

**Comment by damianooldoni** [comment]
Issue solved via #180
