### ISSUE TITLE
Update `read_camtrap_dp()` so it can read Camtrap DP 0.1.6 and 1.0-rc.1

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtraptor#196]
For camtraptor v0.20 we envision `read_camtrap_dp()` to be able to read legacy Agouti exports (Camtrap DP 0.1.6) and new Agouti exports (Camtrap DP 1.0-rc.1) **without affecting the other functions** (i.e. non-breaking change).

To do this, `read_camtrap_dp()` should:

- [x] Detect the version in `package$profile`
- [x] Ignore or deprecate the `media` flag (debatable): decided to not do it in v0.20 (see https://github.com/inbo/camtraptor/issues/196#issuecomment-1632663534)

The required changes are listed below.

## profile

- [x] contributor$role: `author`/`maintainer` are deprecated in 1.0-rc.1, some new roles are added. Ok to leave as is.
- [x] organizations: deprecated in 1.0-rc.1. Ok if missing.
- [x] project$animalTypes: deprecated in 1.0-rc.1. Ok if missing.
- [x] project$individualAnimals: new in 1.0-rc.1. Ok to leave in.
- [x] project$classificationLevel: renamed to `observationLevel` in 1.0-rc.1. Convert to old name.
- [x] project$sequenceInterval: deprecated in 1.0-rc.1. Ok if missing.
- [x] coordinatePrecision: new in 1.0-rc.1. Ok to leave in.
- [x] taxonomic[x]$kingdom, etc: new in 1.0-rc.1. Ok to leave in.
- [x] platform: deprecated in 1.0-rc.1. Look for first element in `sources` and assign `title` as `platform$title`
- [x] rightsHolder: deprecated in 1.0-rc.1. Look for first contributor with role `rightsHolder` and assign `title` as `rightsHolder`
- [x] relatedIdentifiers: new in 1.0-rc.1. Ok to leave in.
- [x] references: new in 1.0-rc.1 (moved from `project$references`, but was never populated for Agouti). Ok to leave in.

## $data$deployments

- [x] deploymentID: same
- [x] locationID: same
- [x] locationName: same
- [x] longitude: order switched
- [x] latitude: order switched
- [x] coordinateUncertainty: same
- [x] start: rename from `eventStart`
- [x] end: rename from `eventEnd`
- [x] setupBy: same
- [x] cameraID: same
- [x] cameraModel: same
- [x] cameraInterval: rename from `cameraDelay`
- [x] cameraHeight: same
- [x] cameraTilt: same
- [x] cameraHeading: same
- [x] detectionDistance: new, ignore
- [x] timestampIssues: same
- [x] baitUse: convert from boolean `baitUse`
- [x] session: deprecated, leave empty
- [x] array: deprecated, leave empty
- [x] featureType: same
- [x] habitat: same
- [x] tags: rename from `deploymentTags`
- [x] comments: rename from `deploymentComments`
- [x] _id: deprecated, leave empty

## $data$media

- [x] mediaID: same
- [x] deploymentID: same
- [x] sequenceID: ~deprecated, leave empty? Not sure if this will break things.~ created by joining `media` and `observations` on `deploymentID` and `timestamp` between `eventStart` and `eventEnd` as proposed in https://github.com/tdwg/camtrap-dp/pull/314
- [x] captureMethod: same
- [x] timestamp: same
- [x] filePath: same
- [x] filePublic: new term, ignore
- [x] fileName: same
- [x] fileMediatype: same
- [x] exifData: same
- [x] favourite: rename from `favorite`
- [x] comments: rename from `mediaComments`
- [x] _id: deprecated, leave empty

## $data$observations

- [x] Filter on `observationLevel = event`
- [x] observationID: same
- [x] deploymentID: same
- [x] sequenceID: rename from `eventID`
- [x] mediaID: same
- [x] timestamp: rename from `eventStart`
- [x] eventEnd: new term, ignore
- [x] observationLevel: new term, ignore
- [x] observationType: same
- [x] cameraSetup: rename from `cameraSetupType`
- [x] taxonID: same
- [x] scientificName: same
- [x] count: same
- [x] countNew: deprecated, leave empty
- [x] lifeStage: same
- [x] sex: same
- [x] behaviour: rename from `behavior`
- [x] individualID: same
- [x] classificationMethod: same
- [x] classifiedBy: same
- [x] classificationTimestamp: same
- [x] classificationConfidence: rename from `classificationProbability`
- [x] observationTags: new term, ignore
- [x] comments: rename from `observationComments`
- [x] _id: deprecated, leave empty
- [x] speed: rename from `individualSpeed`
- [x] radius: cannot be supported before we use the new 1.0 model (decided to read them in if present, see https://github.com/inbo/camtraptor/issues/196#issuecomment-1609592286)
- [x] angle: cannot be supported before we use the new 1.0 model (same as `radius`)
- [x] bboxX: new term, ignore
- [x] bboxY: new term, ignore
- [x] bboxWidth: new term, ignore
- [x] bboxHeight: new term, ignore

**Comment by damianooldoni** [comment]
I would both ignore AND deprecate `media` arg (flag). Done in 7bd21068a1cc379d97a88000795da81c730a4e50

**Comment by damianooldoni** [comment]
After discussion with @peterdesmet, we will:

- support only camtrap-dp packages formatted using versions 0.1.6 and 0.6. Other versions are not supported and an informative message will be returned
- won't load `media-observations` as extra slot of `package$data` as it could be very misleading for the users. It will make things more difficult for us to test the package as `pkg$data` will not contain the same number of slots. Notice that we still make use of `media-observations` for populating the fields `radius` and `angle` in `observations`.

The factor value to use for `baitUse` field will be defined based on values `dep.tags` and boolean `dep.baitUse`:

dep.baitUse | dep.tags | baitUse
--- | --- | ---
`TRUE` | no bait related tags | `other`
`TRUE` | bait related tag NOT among the ones allowed | `other`
`TRUE` | bait related tag among the ones allowed | bait related tag
`FALSE` | ignored | `none` 
`NA` | ignored | `NA`

**Comment by damianooldoni** [comment]
@peterdesmet: about `individualPosition` and `individualAngle`, you wrote:

- `radius`: cannot be supported before we use the new 1.0 model
- `angle`: cannot be supported before we use the new 1.0 model 

We provided a patch to read not-in-schema terms `speed`, `radius` and `angle` present in Agouti exports (#185) following v0.1.6. So, I wonder if we can at the moment still support `radius` and `angle` by renaming from `individualPositionRadius`- `Angle` even if they are not really make sense for event-based observations?

**Comment by damianooldoni** [comment]
Decided to still leave `media` argument as in version v1.0-rc-1 we can still bypass media table to get (event-based) observations.

**Comment by damianooldoni** [comment]
Decided with @peterdesmet to map "new" field `deploymentGroups` to "old" field `session`. This shouldn't have a significant impact at the moment.

**Comment by damianooldoni** [comment]
Notice that `get_record_table()` uses `sequenceID` in `media`. So, we cannot leave it empty. Added via workflow proposed by @peterdesmet in https://github.com/tdwg/camtrap-dp/pull/314.

**Comment by peterdesmet** [comment]
If you retain them, will that effect tests?

**Comment by damianooldoni** [comment]
The only affected test was the one where I check the column names. I run all package functions locally without any issue. Notice that I didn't write new tests for each test. I wrote "only" a lot of new tests for checking that the output of `read_camtrap_dp()` is as expected, and so very similar to the old one.

**Comment by peterdesmet** [comment]
If the bbox columns are the only ones we add, I would ignore them at this stage as they are not part of 0.1.6. Doesn’t feel right to make an exception for just these.

**Comment by damianooldoni** [comment]
Decided with @peterdesmet to remove bounding box related columns as they could be confusing for the user at this stage.

**Comment by damianooldoni** [comment]
Agreed with @peterdesmet: do not add `taxonRank` from taxonomic slot (new term in 1.0-rc.1) while building `.data$observations`.
In this way, the only difference among the columns of `.$data$observations` is the 2 vs 3 letters to indicate vernacular language, e.g. `vernacularName.eng` vs `vernacularName.en`.

**Comment by damianooldoni** [comment]
I see in https://github.com/tdwg/camtrap-dp/blob/ef261578d956e1d3ece78ead760e0bd2d4df81c8/camtrap-dp-profile.json#L231C16-L245 that `taxonRank` is a not required field in `taxonomic` element in *v0.1.6* already and so it is must NOT be removed! The fact that the example datapackage we were using (`mica`) didn' contain it should not allow us to remove it.

**Comment by damianooldoni** [comment]
Contrarely to `taxonRank`, we shouldn't add higher taxonomic classification fields (`kingdom`, `phylum`, etc.) as they are not valid in v0.1.6.

**Comment by damianooldoni** [comment]
Solved by #223
