### ISSUE TITLE
Search results on pkgdown website link to wrong page

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtraptor#197]
1. Go to https://inbo.github.io/camtraptor/index.html
2. Type "Read" in the search bar at the top
3. Click on the first suggested result in the dropdown: `Reference > Read a Camtrap DP — read_camtrap_dp`
4. Result link to: https://inbo.github.io/reference/read_camtrap_dp.html?q=Read#null

Rather than the expected: https://inbo.github.io/camtraptor/reference/read_camtrap_dp.html?q=Read#null

This also affects:

- [ ] https://trias-project.github.io/trias/
- [ ] https://inbo.github.io/movepub/
- [ ] https://inbo.github.io/etn/

`frictionless`, `bioRad`, `wateRinfo` and `rgbif` are not affected.

@PietrH can you debug this one?

**Comment by PietrH** [comment]
I'm having a look

**Comment by PietrH** [comment]
I'm having trouble replicating the issue, it's possibly due to `url: ~` in `_pkgdown.yml`, however I haven't been able to test this hypothesis.

Later on this week I'll have another go at this issue.

**Comment by peterdesmet** [comment]
Oh, that's a good guess. I'm curious if anyone has reported it at pkgdown.

**Comment by PietrH** [comment]
@damianooldoni and I had a brief discussion about this issue today. 

To clarify: I can confirm the issue, but haven't been able to create a new website with pkgdown that has the same problem. 

So far I've been debugging off a fork of existing packages with the issue, but later on this week I'll try starting from a blank slate (a new, repo, a new package). Thanks for the suggestion.

**Comment by PietrH** [comment]
Discussed with @damianooldoni, to move to milestone v1.0

**Comment by peterdesmet** [comment]
This is now fixed. It is indeed necessary to change `url: ~` to an absolute domain name. I have also updated (or recorded to update) the other packages this affects.
