### ISSUE TITLE
update test-read_camtrap_dp.R back to updated version of datapackage.json

### ISSUE THREAD

**Issue by PietrH** [inbo/camtraptor#200]
## context

As per #191 `test-read_camtrap_dp.R` now refers to a specific commit for an example of `camtrap-dp`'s `datapackage.json`:

```r
test_that("file can be an URL", {
  # camtraptor is trailing camtrap-dp, refer to specific commit to keep using old version
  # dp_path <- "https://raw.githubusercontent.com/tdwg/camtrap-dp/main/example/datapackage.json"
  dp_path <-
    "https://raw.githubusercontent.com/tdwg/camtrap-dp/bb046c85a55bef2ced709357c0047f0136df8326/example/datapackage.json"
  dp <- suppressMessages(read_camtrap_dp(
    file = dp_path,
    media = FALSE
  ))
  expect_true(is.list(dp))
  expect_true(all(c("tbl_df", "tbl", "data.frame") %in%
    class(dp$data$deployments)))
  expect_true(all(c("tbl_df", "tbl", "data.frame") %in%
    class(dp$data$observations)))
})
```

- refer to [tests/testthat/test-read_camtrap_dp.R](https://github.com/inbo/camtraptor/pull/191/files/91c584a505e31591855a89229d081ba8e576ddf8#diff-f876128eda4d1baa1ac57cdb43c49b1b96b1e3812409e0e1443d40c49b3b6436)  and `camtrap-dp/main/example/datapackage.json`

We did this because at the time of #191 the test was failing because camtraptor was trailing an older version of camtrap-dp. 

---

## blockers 

This issue is blocked by the neccesairy changes to `read_camtrap_dp.R` and `camtraptor` to use the new schema in general.

## fix

Once camtraptor is ready: `read_camtrap_dp()` is updated to use/support the new schema) the test should be switched back to using the most up to date `datapackage.json` from `camtrap-dp`

**Comment by peterdesmet** [comment]
This is no longer the case in camtrapdp, it refers to a version: https://github.com/inbo/camtrapdp/blob/14cc3cc2b8bf7399feef78f808ab5a62543ed9bb/tests/testthat/test-read_camtrapdp.R#L4
