### ISSUE TITLE
Error while running `get_custom_effort()`

### ISSUE THREAD

**Issue by damianooldoni** [inbo/camtraptor#204]
Question asked by mail from a WUR student.

ik wil een custom effort berekenen (de effort per maand ipv per deployment). Alleen krijg ik een error te zien als ik de custom versie probeer te berekenen:

 ```r
get_custom_effort(
+   package = bardia,
+   start = as.Date("2019-01-01"),
+   end = as.Date("2019-12-31"),
+   group_by = "month",
+   unit = "day"
+ )
Error in `map()`:
ℹ In index: 1.
Caused by error in `dplyr::na_if()`:
! Can't convert `y` <double> to match type of `x` <tbl_df>.
Run `rlang::last_error()` to see where the error occurred.
``` 

Als ik verder alle filters achterwege laat krijg ik dezelfde error:

```r
get_custom_effort(bardia)
Error in `map()`:
ℹ In index: 1.
Caused by error in `dplyr::na_if()`:
! Can't convert `y` <double> to match type of `x` <tbl_df>.
Run `rlang::last_error()` to see where the error occurred.
```
 
Maar als ik de ‘normale’ effort functie gebruik dan geeft hij wel de effort per deployment:

```r
get_effort(bardia, unit = "day")
# A tibble: 794 × 4
   deploymentID                          effort unit  effort_duration         
   <chr>                                  <dbl> <chr> <Duration>              
 1 473b1645-bc4b-4436-95b2-85111c216ed1   67.9  day   5865038s (~9.7 weeks)   
 2 a2fec07f-d0fc-4e8f-b589-23b3f54aa59e  162.   day   13965307s (~23.09 weeks)
 3 e22cf8a5-5900-4701-8791-ce2de6e3311e 1027.   day   88696911s (~2.81 years) 
 4 275ff07d-b774-4e34-a4da-0c3128e5ccb7   33.3  day   2880570s (~4.76 weeks)  
 5 d6e4c249-5ba9-422c-9e12-f8d4fda307d1   29.9  day   2585324s (~4.27 weeks)  
 6 5772535e-8967-4310-af2c-2ab3635d21fc   48.9  day   4227017s (~6.99 weeks)  
 7 a670513c-192b-42e4-be86-dfad667dba0a   30.9  day   2671678s (~4.42 weeks)  
 8 194c83dc-8fd6-479b-82a6-6bfa5b7b1bff   19.3  day   1664026s (~2.75 weeks)  
 9 44954573-5307-4406-be63-f04cd32e15ce   36.1  day   3116361s (~5.15 weeks)  
10 ba27ccb7-6482-4fdc-af38-0574afe8e616    8.08 day   698051s (~1.15 weeks)  
 ```

Nu heb ik op de WUR contact met Yorick als ik tegen problemen aan loop in R, maar hij wist deze keer ook niet waar het probleem zat en rade me aan om jullie een mail te sturen voor advies.

Hebben jullie een idee hoe ik dit op kan lossen?

**Comment by damianooldoni** [comment]
It can be a bug after updating code to meet requirements of new dplyr version.

**Comment by giahanv1999** [comment]
> devtools::session_info()
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.2 (2022-10-31 ucrt)
 os       Windows 10 x64 (build 22621)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.utf8
 ctype    English_United States.utf8
 tz       Europe/Berlin
 date     2023-03-29
 rstudio  2023.03.0+386 Cherry Blossom (desktop)
 pandoc   NA

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 cachem        1.0.6   2021-08-19 [1] CRAN (R 4.2.2)
 callr         3.7.3   2022-11-02 [1] CRAN (R 4.2.2)
 camtraptor  * 0.19.4  2023-02-02 [1] Github (inbo/camtraptor@625a211)
 cli           3.6.0   2023-01-09 [1] CRAN (R 4.2.2)
 crayon        1.5.2   2022-09-29 [1] CRAN (R 4.2.2)
 devtools      2.4.5   2022-10-11 [1] CRAN (R 4.2.2)
 digest        0.6.31  2022-12-11 [1] CRAN (R 4.2.2)
 dplyr       * 1.1.1   2023-03-22 [1] CRAN (R 4.2.3)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.2.2)
 fansi         1.0.4   2023-01-22 [1] CRAN (R 4.2.2)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.2.2)
 fs            1.6.0   2023-01-23 [1] CRAN (R 4.2.2)
 generics      0.1.3   2022-07-05 [1] CRAN (R 4.2.2)
 glue          1.6.2   2022-02-24 [1] CRAN (R 4.2.2)
 htmltools     0.5.4   2022-12-07 [1] CRAN (R 4.2.2)
 htmlwidgets   1.6.2   2023-03-17 [1] CRAN (R 4.2.3)
 httpuv        1.6.8   2023-01-12 [1] CRAN (R 4.2.2)
 later         1.3.0   2021-08-18 [1] CRAN (R 4.2.2)
 lifecycle     1.0.3   2022-10-07 [1] CRAN (R 4.2.2)
 magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.2.2)
 memoise       2.0.1   2021-11-26 [1] CRAN (R 4.2.2)
 mime          0.12    2021-09-28 [1] CRAN (R 4.2.0)
 miniUI        0.1.1.1 2018-05-18 [1] CRAN (R 4.2.2)
 pillar        1.9.0   2023-03-22 [1] CRAN (R 4.2.3)
 pkgbuild      1.4.0   2022-11-27 [1] CRAN (R 4.2.2)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.2.2)
 pkgload       1.3.2   2022-11-16 [1] CRAN (R 4.2.2)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.2.2)
 processx      3.8.0   2022-10-26 [1] CRAN (R 4.2.2)
 profvis       0.3.7   2020-11-02 [1] CRAN (R 4.2.2)
 promises      1.2.0.1 2021-02-11 [1] CRAN (R 4.2.2)
 ps            1.7.2   2022-10-26 [1] CRAN (R 4.2.2)
 purrr         1.0.1   2023-01-10 [1] CRAN (R 4.2.2)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.2.2)
 Rcpp          1.0.10  2023-01-22 [1] CRAN (R 4.2.2)
 remotes       2.4.2   2021-11-30 [1] CRAN (R 4.2.2)
 rlang         1.1.0   2023-03-14 [1] CRAN (R 4.2.3)
 rstudioapi    0.14    2022-08-22 [1] CRAN (R 4.2.2)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.2)
 shiny         1.7.4   2022-12-15 [1] CRAN (R 4.2.2)
 stringi       1.7.12  2023-01-11 [1] CRAN (R 4.2.2)
 stringr       1.5.0   2022-12-02 [1] CRAN (R 4.2.2)
 tibble        3.2.1   2023-03-20 [1] CRAN (R 4.2.3)
 tidyselect    1.2.0   2022-10-10 [1] CRAN (R 4.2.2)
 urlchecker    1.0.1   2021-11-30 [1] CRAN (R 4.2.2)
 usethis       2.1.6   2022-05-25 [1] CRAN (R 4.2.2)
 utf8          1.2.2   2021-07-24 [1] CRAN (R 4.2.2)
 vctrs         0.6.1   2023-03-22 [1] CRAN (R 4.2.3)
 xtable        1.8-4   2019-04-21 [1] CRAN (R 4.2.2)

 [1] C:/Users/giaha/AppData/Local/R/win-library/4.2
 [2] C:/Program Files/R/R-4.2.2/library

**Comment by damianooldoni** [comment]
I see You use version 0.19.4 which indeed suffered of such issue. We solved it in #190 .
Can you please install the package again and check it again? Thanks.

**Comment by PietrH** [comment]
Hi @giahanv1999 , have you been able to solve this by updating? 

You can update like this:
```r
devtools::install_github("inbo/camtraptor")
```

And check if you are on the lastest version like so: 
```r
utils::packageVersion("camtraptor")
```

If you are having trouble updating, or if they problem persists after the update, just let us know and we'll see what we can do to help!

**Comment by giahanv1999** [comment]
No it was solved after updating, thanks! :)
