### ISSUE TITLE
Check there are no missing values in required fields

### ISSUE THREAD

**Issue by damianooldoni** [inbo/camtraptor#216]
This issue was found while searching the origin of a error while running `get_custom_effort`:

```r
> custum_effort_day <- get_custom_effort(NPHK, group_by = "year",
+   unit = "day")
Error in seq.int(0, to0 - from, by) : 'to' must be a finite number
```

A debugging session could easily find the problem: in the function `get_custom_effort` we calculate the max() of `end` values of deployments. `NA` is returned in this case as there is one deployment without `end` value:

```r
> NPHK$data$deployments %>% dplyr::filter(is.na(end)) %>% dplyr::pull(deploymentID)
[1] "bdecbc00-fbda-4d6f-aa06-985b6415f5e3"
```

This issue should be detected asap by the help function `check_package()`. Moreover, this function should not only run at the beginning of the `get_` functions, but it should be run at the end of `read_camtrap_dp()` function and return an error if there are missing values in any of the required fields.

**Comment by peterdesmet** [comment]
Indeed, a `check_package()` function would be really useful.

**Comment by damianooldoni** [comment]
We have it actually 😄 
See https://github.com/inbo/camtraptor/blob/339aad2fc72d0050c37c585c1ec4f9bb33403adc/R/zzz.R#L1-L53 
But it is quite poor at the moment. It is also an internal function. I wonder if we should export it and make it visible to users. I think so.

**Comment by peterdesmet** [comment]
Yeah, we are also envisioning a `frictionless::validate_package()` at some point in the future. I would thus keep the camtraptor version of `check_package()/validate_package()` limited to some key things, rather than being exhaustive.

**Comment by peterdesmet** [comment]
Missing values is is listed as part of an envisioned `validate()` function in camtrapdp: https://github.com/inbo/camtrapdp/issues/58. We can close this one.
