### ISSUE TITLE
get_custom_effort     group_by = "year"     unit = "day"

### ISSUE THREAD

**Issue by jimcasaer** [inbo/camtraptor#219]
at the moment these settings calculate the effort for each 365 days after the selected starting date, calculated as the number of days. This is rather confusing and not often useful for research questions 

suggestion => calculate the effort (in days) for each calendar year

**Comment by damianooldoni** [comment]
Discussed with @jimcasaer: this should be implemented quite soon and so it should be developed at patchlevel: v0.20.1.

**Comment by jimcasaer** [comment]
yes !

Op di 5 sep. 2023 16:30 schreef Damiano Oldoni ***@***.***>:
