### ISSUE TITLE
Correct vignette visualization deployment

### ISSUE THREAD

**Issue by damianooldoni** [inbo/camtraptor#224]
Thanks @peterdesmet to notice the following:

1. Sentence _Notice how zero values are also visualized by a specific circle marker for ease detection. Color: red by default._ seems outdated as the color of the "x" in the leaflet is not red? 
2. There is also a typo: "Tip**l**cally" should be "Tip**y**cally".

**Comment by peterdesmet** [comment]
Correction: typically 😊

**Comment by PietrH** [comment]
I fixed the spelling (already merged), but not the line about the red markers.
