### ISSUE TITLE
Create `deployments()`, `observations()`, `media()` to retrieve data

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtraptor#232]
_Suggested in camtraptor July 2023 coding sprint_

Rationale: provide convenience functions to retrieve the tables/data frames from a camtrap dp object, so users don't have to retrieve them from `package$data$tablename`. Benefits:

- Easier to understand than `package$data$tablename`
- Retrieving data is an important functionality, so should be tested
- Can be used by other functions that need to access the data
- Allows to change data model without affecting functionality
- Is in line with other suggested functions to retrieve data, such as `taxonomy()`, `locations()`, `events()`

**Comment by PietrH** [comment]
@damianooldoni can this be closed?
