### ISSUE TITLE
Rename `get_cam_op()` to `camtrapR_cameraOperation()`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtraptor#239]
_Suggested in camtraptor July 2023 coding sprint_

Rationale: get functions are mixed bag, now same name as in camtrapR without masking. Some parameters should be removed as well.

```R
camtrapR_cameraOperation(
  package = NULL,
  # ... removed, see filter functions
  station_col = "locationName",
  use_prefix = FALSE
  # datapkg removed
)
```

**Comment by damianooldoni** [comment]
Fixed by PR #331.
