### ISSUE TITLE
Rename `get_record_table()` to `camtrapR_recordTable()`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtraptor#240]
_Suggested in camtraptor July 2023 coding sprint_

Rationale: get functions are mixed bag, now same name as in camtrapR without masking. Some parameters should be removed as well.

```R
camtrapR_recordTable(
  package = NULL,
  # ... removed, see filter functions
  stationCol = "locationName",
  exclude = NULL,
  minDeltaTime = 0,
  deltaTimeComparedTo = NULL,
  removeDuplicateRecords = TRUE
  # datapkg removed
)
```

**Comment by damianooldoni** [comment]
Completed by PR #331.

**Comment by damianooldoni** [comment]
Reopen this issue as it's not only a question of renaming. We need to refactoring. Work on this in branch [`camtrapR-like-outputs`](https://github.com/inbo/camtraptor/tree/camtrapR-like-outputs).

**Comment by damianooldoni** [comment]
Also, refactor the tests.
