### ISSUE TITLE
Create `update_deployments()`, `update_media()`, `update_observations()` to update dataframes

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtraptor#248]
_Suggested in camtraptor July 2023 coding sprint_

#232 provides convenience functions to retrieve data. The user might want to alter the data (e.g. adding a column, fixing an error) and attach these back to the data package.

```R
df <- observations(package)
# changes to df
update_observations(package, df)
```

- Adding additional columns is fine, those can be ignored/added in separate tables in a `write_camtrap_dp()` to make it align with Camtrap DP again
- It might be necessary to run some validation functions (optional?) to make sure columns are still in the expected data type and relationships exist
- Alternative names for the functions could be:

```R
update_package(package, "observations", df) # maybe too verbose
# or
observations(package) <- df # I'm quite a fan of this approach, but might not be intuitive to user
```

**Comment by damianooldoni** [comment]
_Suggested in camtraptor July 2024 coding sprint_

Is there a need in camtrapdp to do also manipulations? It seems in scope with the goal of the package.
Similarly to `filter()` we can then reexporting such functionality.

**Comment by peterdesmet** [comment]
These functions are available already, as accessor functions (e.g. [`deployments()<-`](https://inbo.github.io/camtrapdp/reference/deployments.html)). As mentioned in the function documentation:

> `deployments<-()` is the assignment equivalent. It should only be used within other functions, where the expected data structure can be guaranteed.

It's not great to provide these to users, as it can break the internal logic between the tables, so I would not reexport them in camtraptor.

**Comment by damianooldoni** [comment]
Of course! we have them already in camtrapdp. So, this issue can be closed as it is not camtraptor related anymore and already solved in camtrapdp actually.
