### ISSUE TITLE
is number of interval of scale in map_dep() fixed

### ISSUE THREAD

**Issue by jimcasaer** [inbo/camtraptor#25]
in most of the examples a 5-point scale is used 
however in some more intervals do appear 

how/where is this fixed ?

**Comment by damianooldoni** [comment]
Sorry the late answer! 
Yes, this is at the moment hardcoded and set to 6 bins in `map_dep.R`, see [line 460](https://github.com/inbo/camtrapdp/blob/main/R/map_dep.R#L460). I chosed it to avoid too big default legends.

@jimcasaer: do you want an arg to allow the user to fine tune this? May I leave 6 as default value?

**Comment by damianooldoni** [comment]
We close this issues at the moment. If changes on number of intervals is needed, please open a new issue.
