### ISSUE TITLE
Delete `write_eml()`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtraptor#250]
_Suggested in camtraptor July 2023 coding sprint_

`write_eml()` and `write_dwc()` were developed to convert Camtrap DP to Darwin Core Archives, which could then be uploaded to the [IPT](https://www.gbif.org/ipt). Now that the IPT supports the publication of Camtrap DP (data + metadata) natively, there is limited need for the EML conversion. Rather, we should help users in reading (cleaning and writing) Camtrap DP files.

The `write_dwc()` function however is still needed, as it will be used by GBIF to convert Camtrap DPs published through the IPT to Darwin Core data that can be ingested as occurrences. GBIF does not use the `write_eml()` function, but will directly parse the `datapackage.json` metadata to their metadata registry. Removing the `write_eml()` function from camtraptor frees up time to develop, maintain and write tests for other functions.

Users who want to publish their camera trap data from Camtrap DP to Darwin Core still can by:

1. Loading their Camtrap DP export with `read_camtrap_dp()`
2. Using `write_dwc()` to convert the data (or do it using their own transformation)
3. Uploading the files to the IPT
4. Manually adding the EML metadata

**Comment by damianooldoni** [comment]
`write_eml()` is developed in camtrapdp package (see https://inbo.github.io/camtrapdp/reference/write_eml.html). At the moment no need to reexport it in camtraptor.
