### ISSUE TITLE
Remove `media` argument from `read_camtrap_dp()`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtraptor#255]
_Suggested in camtraptor July 2023 coding sprint_

`read_camtrap_dp()` currently has a `media` flag, which is `TRUE` by default:

> If `TRUE`, read media records into memory. If `FALSE`, ignore media file to speed up reading larger Camtrap DP packages.

As indicated, this flag was added to speed up reading packages. And in Camtrap DP v1.0-rc.1 it is still possible to do most operations without `media`, but **having media optional makes it more complex for functions downstream**, including:

- `filter_` functions are expected to filter media and would need functionality to skip this inbo/camtrapdp#23
- `media()` and `update_media()` function should handle when no media are present inbo/camtraptor#232 inbo/camtraptor#248
- `convert_` functions which are automatically called from `read_camtrap_dp()` inbo/camtrapdp#9
- `write_camtrap_dp()` should have media to be valid, if missing user has to start over from scratch inbo/camtrapdp#74
- other?

It is therefore worth considering having a slower `read_camtrap_dp()` (where media are always read) in favour of less complexity downstream. Initial tests indicate that reading is the slowest part, having to manipulate the `media` data frame as part of filters is quite fast (tested for 3.6 million images).

Alternatively, a `check_media()` helper function could be created and called for those functions that require media. If missing, it could return an error to the user suggesting:
- To start over with `read_camtrap_dp(media = TRUE)`: easy to implement, annoying to user
- To load media into the package with `load_media()`: this assumes the media data are still present in `$directory`. This can get quite complex however, since `convert_` functions might need to be called.

Note also that when loading an older version of Camtrap DP, the convert functions might require media to be loaded, resulting in:

```R
read_camtrap_dp("datapackage.json", media = FALSE)
# Error: you are trying to load an older version of Camtrap DP and media need to be loaded ...
```

**Comment by damianooldoni** [comment]
Geetting back on this issue: based on the nice report of @peterdesmet here above and the things  Iremember from the previous sprint, we should opt for the easiest solution, i.e. removing `media` argument from `read_camtrap_dp()`. We are already introducing breaking changes in v1.0 so I would not bother too much about this.

@peterdesmet, @PietrH: do you agree on this?

**Comment by peterdesmet** [comment]
Yes, I agree, remove the `media` parameter. We can optimize (mostly reading) speed in other ways if needed (e.g. through col_select).

**Comment by damianooldoni** [comment]
To be done on branch [remove-media-arg](https://github.com/inbo/camtraptor/tree/remove-media-arg)

**Comment by damianooldoni** [comment]
Remove `media` from the following functions and their related tests:

- [] `read_camtrap_dp()`
- [ ] `check_package()`
- [ ] `check_species()`
