### ISSUE TITLE
Add news.md

### ISSUE THREAD

**Issue by damianooldoni** [inbo/camtraptor#268]
we have to start a news.md for v1.0. Use frictionless's news as inspiration.

**Comment by damianooldoni** [comment]
As @PietrH wrote in https://github.com/inbo/camtraptor/pull/269#issue-1879750743, the news.md will iteratively increased and will become quite big. I think a trimming could follow just before the final release of v1.0 as I assume that not all bullet points are even important.

**Comment by PietrH** [comment]
Agreed, so merge this branch into `v1.0` and remove and start documenting changes from `v1.0` onwards.
