### ISSUE TITLE
Create hex logo

### ISSUE THREAD

**Issue by damianooldoni** [inbo/camtraptor#270]
I think the launching of v 1.0 is worth of a hex logo. @peterdesmet: I still remember the draft you made with the velociraptor pushing the button of an old fashion camera. If somebody with such a bad memory as me still remember it, means it is a good catchy hex logo.

I am still open to other ideas if somebody has.

**Comment by NeleMullens** [comment]
Hi, 

Pieter told me that you were looking for a logo for camtraptor. I came up with a few idea's. Don't worry if you don't like them. Let me know what you think.

![camtraptor_idea_1](https://github.com/inbo/camtraptor/assets/48283120/98c06180-5812-416e-995e-d4dc4453e254)

![camtraptor_idea_2](https://github.com/inbo/camtraptor/assets/48283120/0a68dbb1-6b8e-49ca-a1d1-29fdff44e12c)

**Comment by damianooldoni** [comment]
Lovely! Thanks @NeleMullens to help us with this. 
I will come up back to this issue next week, I hope. I am all week in a conference.

**Comment by NeleMullens** [comment]
Hi again, here is an updated version of the logo (with and without text). Let me know what you think and what I can improve!
![Camtraptor logo](https://github.com/inbo/camtraptor/assets/48283120/ec14fa61-8f1a-449d-ad49-c998af620b6f)
![Camtraptor logo met tekst](https://github.com/inbo/camtraptor/assets/48283120/1afa95b6-ebdc-4fa4-9c79-5cbd8f834d6e)

**Comment by PietrH** [comment]
There is a little smudge on the upper right corner. Is it possible the whole hexagon is rotated slightly?

**Comment by PietrH** [comment]
I've made some changes to the hexagon border and made the background transparant. 

![camtraptor_logo](https://github.com/inbo/camtraptor/assets/48065851/bb1cff7a-fa42-44af-b880-21f8976e586b)

**Comment by PietrH** [comment]
![camtraptor_logo_lexend](https://github.com/inbo/camtraptor/assets/48065851/f572db97-c334-4748-9412-75c9ad6f2a19)

Discussed it in the room, came to this result.

**Comment by PietrH** [comment]
Feedback from the room, the blue is quite strong. Maybe a lighter shade?
