### ISSUE TITLE
retire `path` argument from `read_camtrap_dp()`

### ISSUE THREAD

**Issue by PietrH** [inbo/camtraptor#276]
Discussed with @damianooldoni and @peterdesmet , we will be retiring the `path` argument from `read_camtrap_dp()`

- [x] remove `path` argument from `read_camtrap_dp()`
- [x] remove `path` argument from `read_camtrap_dp()` documentation
- [x] remove `path` argument test from `test-read_camtrap_dp.R`
- [x] Check if the `path` argument is referenced in other functions

**Comment by damianooldoni** [comment]
I think you can now close this issue as completed.
