### ISSUE TITLE
add number of individuals to output of `get_record_table`

### ISSUE THREAD

**Issue by jimcasaer** [inbo/camtraptor#279]
for some analyses, it would be great to have not only the scientific name of the observed species but also the number of individuals in the observation, as well as the age class and sex 

these could be extra information in t he tibble data frame resulting from the get_record_table() and would avoid extra coding and merging afterwards

**Comment by damianooldoni** [comment]
After meeting with @jimcasaer and @MartijnUH on Oct 23, decided to add only number of individuals to output of `get_record_table()`. Title of the issue has been updated.

Notice that the record table is something that we produce to mimick the record tables created in camtrapR package and to use as input of other camtrapR functions. This column is still not part of camtrapR and so we will ping the camtrapR's maintainer we think it's worth having such column added.
