### ISSUE TITLE
Add support for Camtrap DP 1.0

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtraptor#284]
Camtrap DP 1.0 has been released: https://github.com/tdwg/camtrap-dp/releases/tag/1.0. We're planning to update the Agouti export to Camtrap DP 1.0 directly (and not have 1.0-RC.1). Before we can release that Agouti export however, **camtraptor needs to be updated to support 1.0**, otherwise users won't be able to read the data.

- [x] Update [convert_to_0.1.6()](https://github.com/inbo/camtraptor/blob/db6c53ab563c095064ee10a8728447f1b4aa8e42/R/zzz.R#L440) and support `1.0` _instead_ of `1.0-rc.1` (this version never made it to production in Agouti or IPT)
- [x] `observations.taxonID` has been removed, downconvert by including in observations (leave empty)
- [x] `deployments.cameraDepth` has been added, downconvert by removing it
- [x] Update https://github.com/inbo/camtraptor/blob/db6c53ab563c095064ee10a8728447f1b4aa8e42/R/zzz.R#L400 to only join on `scientificName` (since Camtrap DP 1.0 no longer has `taxonID`)
- [x] Downconvert `media.captureMethod` values `activityDetection` to `motionDetection`
- [x] Downconvert `project.catureMethod` (in metadata) values `activityDetection` to `motionDetection`
- [ ] Pass all tests

**Comment by PietrH** [comment]
> version is not supported ...

https://github.com/inbo/camtraptor/blob/db6c53ab563c095064ee10a8728447f1b4aa8e42/R/read_camtrap_dp.R#L97-L107


`convert_metadata_to_0.1.6()`:  

https://github.com/inbo/camtraptor/blob/db6c53ab563c095064ee10a8728447f1b4aa8e42/R/zzz.R#L431-L484

**Comment by PietrH** [comment]
## Differences between RC and v1.0

- `taxonID` has been removed from observations, we need to create this field for version v0.1.6 
How will we populate this field?

Peter proposes to leave it empty. So add it but leave it empty.

The function that links the taxonomy with the observations (`add_taxonomic_info()` -> `get_species()`)

https://github.com/inbo/camtraptor/blob/db6c53ab563c095064ee10a8728447f1b4aa8e42/R/zzz.R#L400

Needs to change to only join on `scientificName`

- Do we need additional tests? Unclear if all changes are covered

**Comment by PietrH** [comment]
example package to test on: https://github.com/tdwg/camtrap-dp/tree/main/example
