### ISSUE TITLE
Bug multi-session and counts detectionHistory

### ISSUE THREAD

**Issue by MartijnUH** [inbo/camtraptor#287]
The detectionHistory() function of camtrapR does not work with arguments `output = "counts"` and `unmarkedMultFrameInput = T`.

**Comment by damianooldoni** [comment]
@MartijnUH: we discussed this in our meeting today, indeed. Sitll, I think it is not an issue for camtraptor. But it can be that I was not clear during our meeting.

**Comment by MartijnUH** [comment]
> @MartijnUH: we discussed this in our meeting today, indeed. Sitll, I think it is not an issue for camtraptor. But it can be that I was not clear during our meeting.

@damianooldoni I agree with that. Where should I reference this issue instead? Or do I just send you a minimal data example?

**Comment by damianooldoni** [comment]
Just via mail. And if you prefer add a note in our Gdoc. Sorry, I think I misunderstood you druring our meeting few minutes before.
