### ISSUE TITLE
Extend functionality of `get_cam_op`: allow `sessionCol` argument to add `sessionID` in `stationName` column as in camtrapR

### ISSUE THREAD

**Issue by MartijnUH** [inbo/camtraptor#288]
Naming convention in camtrapR: **stationID__SESS_sessionID**
_expample: Station1__SESS_2019_

See https://jniedballa.github.io/camtrapR/reference/cameraOperation.html

**Comment by damianooldoni** [comment]
Thanks @MartijnUH.

Some extra words for my maintainer mates, @peterdesmet  and @PietrH.

This issue/feature request came up during the meeting hold with @MartijnUH and @jimcasaer on Monday, Nov 11, in the framework of my support of their modelling research.

The label "urgent" means that this feature will be implemented as version 0.20.x. We all know that it's better to change things after the release of camtraptor v1.0 which is also something urgent, especially now that camtrapdp v1 has been officially released. 

However, this feature is:
- very limited on scope (it doesn't impact the work for the release camtraptor v1)
- important for making progress in multiseason research

**Comment by PietrH** [comment]
Let me know if you need any help or input Damiano.

**Comment by PietrH** [comment]
I will review all the things! :hamster:

**Comment by damianooldoni** [comment]
Whiel working on this in #289 I noticed that we could easily add the similar argument `camera_col` and so to be even more camtrapR compliant. Probably something we do not really need but I think it's better to do it now than having to add it at a later stage.

Convention used in camtrapR implemented: `Station__SESS_SessionID__CAM_CameraID`

**Comment by damianooldoni** [comment]
I also check that the words  `__SESS_` and `__CAM_` are not present in `station_col`, `session_col` and `cam_col`. Again, this is to follow the [guidelines](https://jniedballa.github.io/camtrapR/reference/cameraOperation.html) of camtrapR.
