### ISSUE TITLE
Take radius/angle from first media-based observation and assign at event-level when down-converting

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtraptor#291]
@MarcusRowcliffe asks:

> With this fix [correct eventStart/eventEnd for media-based observations), will camptraptor down-versioning to CamtrapDP 0.1.6 then correctly take IndividualPosition values from the first position of each observation to populate the radius and angle fields in the observations table? Currently those fields are not being filled in the output of `read_camtrap_dp()`.

@damianooldoni how are media-based observations currently treated when down-converting to Camtrap DP 0.1.6?

**Comment by damianooldoni** [comment]
At the moment we work only with event-based observations. See https://github.com/inbo/camtraptor/blob/main/R/zzz.R#L746-L748.
Media-observations are removed.

**Comment by peterdesmet** [comment]
Ok, in that case we change that to at least retrieve the angle and position. Pseudo code:

1. Select media-based observations
2. Group by `eventID`, take the lowest `eventStart` and from that record take `angle`/`position`
3. Join this information on `eventID` with the event-level observations

**Comment by damianooldoni** [comment]
Thanks @peterdesmet to give me an interesting test datapackage 👍  

I would group by `eventID` AND `individualID` to make the groups unique.

**Comment by damianooldoni** [comment]
To notice also that in case of one-to-one relation between event and media based observations, we will populate `radius` and `angle` but `speed` will be left empty (`NA`) in `.data$observations`. It seems perfectly valid to me.

**Comment by MarcusRowcliffe** [comment]
Please note a problem I have flagged when individualID is used to as a global individual identifier, registered here: [https://git.wur.nl/y.liefting/agouti/-/issues/1025]. Grouping by eventID + individualID is good if individuals are re-recorded between events, but if indivduals create multiple observations within an event (=Agouti sequence), individualID as observation identifier is over-written by global individualID and the observations are no longer distinguishable. Any thoughts?
