### ISSUE TITLE
lifewatch logo is broken in authors pkgdown page

### ISSUE THREAD

**Issue by PietrH** [inbo/camtraptor#313]
https://inbo.github.io/camtraptor/authors.html

![image](https://github.com/inbo/camtraptor/assets/48065851/1c21c46c-1f1f-4d5c-a93c-e787a0c0568f)

**Comment by PietrH** [comment]
Also broken on other lifewatch packages pkgdown websites:

https://docs.ropensci.org/frictionless/

![image](https://github.com/inbo/camtraptor/assets/48065851/e60a1fec-525d-487b-990f-1a9c025f0f89)

**Comment by damianooldoni** [comment]
See https://github.com/frictionlessdata/frictionless-r/commit/9af0da8d0528c65b474ad498f9f5ff12a7f7d1bd

**Comment by damianooldoni** [comment]
This issue has been solved via https://github.com/inbo/camtraptor/commit/48c9a574877680dc4e49839c1594b99a303fc45c. Version 1.0 will contain the correct logo.
