### ISSUE TITLE
remove `round_coordinates()` and `write_dwc()`

### ISSUE THREAD

**Issue by sannegovaert** [inbo/camtraptor#327]
The functions `round_coordinates()` and  `write_dwc()` are moved to camtrapdp and upgraded, so should be removed from camtraptor.
Now this gives an issue when loading both packages:
```
Attaching package: ‘camtraptor’

The following objects are masked from ‘package:camtrapdp’:

    round_coordinates, write_dwc
```

**Comment by damianooldoni** [comment]
Indeed, @sannegovaert. They will be removed in version 1.0. `write_dwc()` is already removed in [version-1.0](https://github.com/inbo/camtraptor/tree/version-1.0) branch. I will remove `round_coordinates()` in the next PR to `version-1.0`.

**Comment by damianooldoni** [comment]
Done in PR #331.

**Comment by damianooldoni** [comment]
I am making this functions **defunct** in #391. Better than just removing them.
