### ISSUE TITLE
Give a special color to value 0 in visualization of all deployment features

### ISSUE THREAD

**Issue by damianooldoni** [inbo/camtraptor#34]
After meeting with @jimcasaer, we decided to give color black to value 0 in `map_dep()` as it is a special/sentinel value.  This should affect the visualization of all features (rai, n_species, effort, n_obs)

**Comment by damianooldoni** [comment]
I think also that the choice of the palette should still be left to the user by adding the argument `palette` to `map_dep()`.
@jimcasaer: the choice of the favourite palette (see comment above) is sitll important as we can use it as default palette.

**Comment by damianooldoni** [comment]
Update: I implemented my solution in #80 so everybody can test it easily by installing from main directly. Default palette: `"inferno"`.

**Comment by jimcasaer** [comment]
@damianooldoni sorry for the long delay before taking this up 
when do you have 5 minutes to discuss this before approving?

**Comment by damianooldoni** [comment]
We decided to try to get a second layer with only the zeros and those ones with a special marker or symbol. In this way are the zero values easily detectable.

**Comment by damianooldoni** [comment]
@jimcasaer: in #84 I tackled this issue again. Can you give a look to the results as shown in vignette: https://inbo.github.io/camtrapdp/articles/visualize-deployment-features.html

If you are satisfied with this kind of marker, we can close this issue and give a party 🥳

**Comment by jimcasaer** [comment]
hmm, the markers are very big !! and blur the total view of the map -- so to be honest: not yet fully satisfied 
no party time yet 

what about using simple circle markers in a specific color for the subset of locations with "0" values

**Comment by jimcasaer** [comment]
@damianooldoni preference for option 4 -- only wondering if red or white would not be better given the background colours of the maps

the suit is almost sold, difficult client

**Comment by damianooldoni** [comment]
Let's give a try!

## white - default opacity

default opacity is way too low, I think.

![image](https://user-images.githubusercontent.com/33662631/156465312-017c0443-1b7d-4b05-9eae-1d11c5040457.png)

## white - high opacity

Better, but it doesn't stand out, I think.

![image](https://user-images.githubusercontent.com/33662631/156465488-d0347d23-5233-41f7-98ab-f74ce4945c79.png)

## red - default opacity

![image](https://user-images.githubusercontent.com/33662631/156465898-3414ad7f-b51f-4d4b-b118-4c5f65899c1a.png)

## red - high opacity 

![image](https://user-images.githubusercontent.com/33662631/156466393-0e1234fb-804c-4fbf-911e-d42f000d1c07.png)


Personally I find red with high opacity the best one. But, be careful: it's the best one if we use default palette! If a user opts for example for `palette = "reds", I think making red circles is not the best option anymore. 

**Proposal**: as we allow the user to pass a different palette than the default one, I strongly recommend to allow him/her to define also the color of these new circles if red is not good.

**Comment by jimcasaer** [comment]
damiano,

my personal preference is the red - default opacity :-) 
and yes I like the idea of to have a default palette and default red -- but allowing the user to indicate other palettes and other colours

**Comment by damianooldoni** [comment]
Great! I will do.

**Comment by damianooldoni** [comment]
@jimcasaer: done  and merged to main in #86. Online documentation and vignette should be automatically updated on the website within few minutes. Let me know what do you think about it.

**Comment by jimcasaer** [comment]
could it be that the red inside/outside is reversed in comparison to example 3  ?

**Comment by damianooldoni** [comment]
I have just given a look to the leaflet maps in https://inbo.github.io/camtrapdp/articles/visualize-deployment-features.html
It seems everything works as expected. The stroke is more opaque than the circle as expected. Or would you like less opacity of the inner circle in general?

**Comment by jimcasaer** [comment]
works fine now outside of markdown -- :-)
final ideas
- should we not allow a option to cluster also the zero - deployments (cfr non-zero values)
- can the cluster function apply on both zero values and non zero values in the leaflet (I guess not given that the are in reality separate layers in this approach)

**Comment by damianooldoni** [comment]
The cluster option already exists. By default is `cluster = TRUE`. You can deactivate clustering via `cluster = FALSE`. it's very easy to add clustering to cluster deployments with zero values as well.

But I would avoid to allow a mix behavior, i.e. `cluster = TRUE` for deploys with zero values and `cluster = FALSE` for all other deployments or viceversa. It will result in adding another argument to the function and I don't think you will ever user it. Do you agree on this?

**Comment by damianooldoni** [comment]
I think I misunderstood your request in my previous comment., @jimcasaer. 
We can cluster zero values deploys and non zero values deploys apart (as explained in my comment above, and as I will push on main in a while). But we can **NOT ** cluster zero and non-zero values deploys together as they are two different layers, indeed.

A small but maybe important graphic decision. 

Do you prefer non-zero deploys on top of zero ones (option 1):

![image](https://user-images.githubusercontent.com/33662631/156796758-087e5491-79c1-4f4a-a0c1-91cea2ab9f71.png)

Or viceversa (option 2)?

![image](https://user-images.githubusercontent.com/33662631/156797287-ea9d7a47-49cf-4065-a462-f662c4b885f5.png)

I think option 1, but I would like your opinion on this. Thanks.

**Comment by damianooldoni** [comment]
@jimcasaer: Pull Request #87 implements option 1 as described in my comment above. Give me your ok and I can push it to main.

**Comment by jimcasaer** [comment]
when do you have a moment
looks like clustering is not working on both layers

**Comment by damianooldoni** [comment]
Well, @jimcasaer, it cannot work on main branch as I have still not pushed to main. Should I?

**Comment by damianooldoni** [comment]
after videocall with @jimcasaer we decided to go for option 1. Unfortunately the merged PR #87 implemented the worng option (option 2). A fast PR is following.

**Comment by damianooldoni** [comment]
@jimcasaer: does everything work fine now? I hope so. Please let me know. Hopefully we can close this issue.

**Comment by jimcasaer** [comment]
you can close it :-) 
good start for the weekend

**Comment by damianooldoni** [comment]
After @jimcasaer brainstorming with his colleagues, we decided to:
1. add show not show argument (default: show)
2. marker type (default = small cross)
3. marker color (default = white)

**Comment by jimcasaer** [comment]
given the standard palette used in map_dep I would suggest to go for a default black and for the smallest symbol (and now I hope the female part of our team will agree :-) )

**Comment by damianooldoni** [comment]
Thanks a lot. Could you please check this with your team (or its female part of it) and give me the final GO?

**Comment by jimcasaer** [comment]
@damianooldoni cluster = FALSE seems to give an error when using map_dep

**Comment by damianooldoni** [comment]
Yes, you are right. I tried to change this

```r
clusterOptions = if (cluster == TRUE) leaflet::markerClusterOptions() else NULL
```

with this:

```r
clusterOptions = ifelse(cluster == TRUE,
                                leaflet::markerClusterOptions(),
                                NULL
        )
```

but R said NO 😄 

I revert it and everything should look good again.

**Comment by damianooldoni** [comment]
Done in https://github.com/inbo/camtraptor/commit/7039d97445e699c2f8acccec7e6402d162ce4265 directly on `main`. Please reinstall and let me know.
