### ISSUE TITLE
Large Files via google -- sollution for files is ok -- what about directories (read_camtrap_dp())

### ISSUE THREAD

**Issue by jimcasaer** [inbo/camtraptor#50]
via the R-packages googledrive and here we can the problem of pushing very large datafiles to github, using tokens (see below)
however no idea how we apply this on the read_camtrap_dp() function -- ideas ? 

e.g. reading files from googledrive 

library(googledrive)
library(here)

## Lees een bestand dat reeds op gdrive staat ##
# Maak een tijdelijke map en datafile waarin je de data zal downloaden
filepath <- here(tempdir(),"data.csv")

# Toke zoeken: deze  vind je al volgt terug:
# 1: Rechtermuis op het bestand op de drive 
# 2: Kies link ophalen 
# 3: extraheer de token uit de link
# link: https://drive.google.com/file/d/<token>/view?usp=sharing

drive_bestand <- "1tgwDb1mpjqU9qZ7pZq5v9x4k5CzbvHeb"

# Download de data

drive_download(as_id(drive_bestand),
               path = filepath,
               overwrite = TRUE)

# Lees de data vanaf de tijdelijke locatie:
data <- read_delim(filepath, ";")

**Comment by damianooldoni** [comment]
No news about this. I suppose it's solved. We will not support working with Gdrive at the moment. 
Issue closed, reopen or write a new, updated one if needed.
