### ISSUE TITLE
Don't use @importFrom in Roxygen but call functions with pkgname::function

### ISSUE THREAD

**Issue by damianooldoni** [inbo/camtraptor#72]
See similar issue in etn package: https://github.com/inbo/etn/issues/240.
Notice this doesn't apply for `%>%` or `!!` or any other special operator.

**Comment by peterdesmet** [comment]
> Notice this doesn't apply for %>% or !! or any other special operator.

If you don't want it to apply for those special operators, then you have to specifically say so in a camtrap-package.R file, cf.: https://github.com/frictionlessdata/frictionless-r/blob/6d4d988e9e828abeaeb6761a814d59f40c8ca28b/R/frictionless-package.R#L1

**Comment by damianooldoni** [comment]
Yes, @peterdesmet, thanks to pointing this. I have already implemented this in the new function which we going to add to `main` via #70. See https://github.com/inbo/camtrapdp/blob/70-custom-trap-effort/R/get_custom_effort.R#L23
