### ISSUE TITLE
Create internal function to join tables within a Camtrap DP

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtraptor#93]
Currently, the business logic of how tables in a Camtrap DP are joined is spread over many functions. I think we should have a single internal function where that logic is expressed. The function can be called by any `get_` function that requires joins between tables. This will also make it more easier to update once the Camtrap DP structure changes (see https://github.com/tdwg/camtrap-dp/issues/203).

**Comment by peterdesmet** [comment]
I still think such a function is a good idea. It could either be used by many functions (recreating the big data frame every time) or by read functions only (`read_camtrap_dp()` and `read_wi()`) which would attach the df to package.

**Comment by damianooldoni** [comment]
Yes, @peterdesmet. I said it to you already some weeks ago, but I would like to write it as well. This is definitely a good idea as the package would be resilient against any kind of changes of the Cameratrap DP changes.
I am in favor of joining within functions at the moment as for some functions only one join is needed, e.g. between obs and deployments, without joining by media. Not only, if we apply `filter()` before `get()` functions (see #92), the needed joins will be quite smaller.

**Comment by peterdesmet** [comment]
Note that in the new version of Camtrap DP, you will always have to join over media.

**Comment by damianooldoni** [comment]
Yes, you are right!

I will have to make some tests with big data packages to see what is the most performant solution time/space wise.

**Comment by peterdesmet** [comment]
See https://github.com/inbo/camtraptor/issues/202#issuecomment-1516160240: it is still good to have a hidden join function, but it should be called by specific functions. It should not be called by `read_camtrap_dp()` to create a single df early on.

**Comment by peterdesmet** [comment]
There is less of a need for this with Camtrap DP 1.0-rc.1, since observations are directly linked to deployments. Moving this to 1.0 milestone, where it needs to be assessed if this is still necessary.

**Comment by peterdesmet** [comment]
_Suggested in camtraptor July coding sprint_: there is no need to join tables internally, they can be kept separate and will be reported separately to the user.
