### ISSUE TITLE
Requesting three extra values for observationType

### ISSUE THREAD

**Issue by PatrickAJansen** [inbo/camtraptor#96]
It would be logical and practical for users to adopt three additional values of observationType in observations.csv

(1) "timelapse", for sequences that can be classified as time-lapse photos.
Currently, timelapse sequences are recorded as observationType="unclassified". They can only be recognized as time lapse only by checking media.csv for captureMethod="time lapse", which is highly unpractical and not logical. 

(2) "setup" and "pickup", for sequences that mark the start and end of the deployment.
Currently, these are recorded as observationType="unclassified" with cameraSetup="TRUE".
If we make this simple change, there is no longer any need for a separate variable cameraSetup.

(3) "calibration", for sequences with markers placements for the purpose of calibration.
Currently, these sequences are recorded either as observationType="human", or as observationType="unclassified" with cameraSetup="TRUE".
It is important that these sequences can be distinguished as calibration sequences.

**Comment by peterdesmet** [comment]
@PatrickAJansen since this issue relates to the standard itself, I have copied your request to that repository: https://github.com/tdwg/camtrap-dp/issues/207. I will close the issue in this repository.
