### ISSUE TITLE
problem with detectionHistory when using camera operation and record table resulting from camtraptor

### ISSUE THREAD

**Issue by jimcasaer** [inbo/camtraptor#99]
when applying this camtrapR function the day1 settings only work for a specific date 
using "station" seems not to function as it should

Dethist_18_wb <- detectionHistory(recordTable = rec_table_2018,
                               camOp = cam_op_2018,   
                               stationCol = "Station",
                               speciesCol = "Species",
                               recordDateTimeCol = "DateTimeOriginal",
                               recordDateTimeFormat ="%Y-%m-%d %H:%M:%S",
                               species = "Sus scrofa",
                               occasionLength = 1,
                               day1 = "survey",
                               datesAsOccasionNames = FALSE,
                               occasionStartTime = 7,
                               includeEffort = FALSE,
                               timeZone = "UTC",
                               writecsv = FALSE)

**Comment by damianooldoni** [comment]
Note for me, an anchor for further debugging.
I think I found the source of the bug while using camtraptor's camop en record tables.

In row 214 of camtrapR::detectionHistory:

```r
Browse[2]> effort.tmp <- do.call(calculateTrappingEffort, arg.list0)
Browse[2]> effort.tmp
[[1]]
                              [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
B_DL_val 5_beek kleine vijver   NA   NA   NA   NA   NA   NA   NA   NA   NA     5    NA
B_DL_val 3_dikke boom           NA   NA   NA   NA   NA   NA   NA   NA   NA    NA    NA
```
Effort of `B_DL_val 3_dikke boom` is all set to NA, why?

**Comment by damianooldoni** [comment]
Notice that in above comment that `cam.min` is set to `2020-06-19` and `cam.max` is set to `2020-06-19` for both camera's, which is not true. 

While debugging the example in camtrapR package, the `cam.min` and `cam.max` are correct:

```r
Browse[2]> date_ranges
            rec.min    rec.max    cam.min    cam.max start_first_occasion start_first_occasion_survey
StationA 2009-04-10 2009-05-06 2009-04-02 2009-05-14           2009-04-02                  2009-04-02
StationB 2009-04-15 2009-04-27 2009-04-03 2009-05-16           2009-04-03                  2009-04-02
StationC 2009-04-24 2009-04-24 2009-04-04 2009-05-17           2009-04-04                  2009-04-02
         end_of_retrieval_day   end_last_occasion
StationA  2009-05-14 23:59:59 2009-05-14 23:59:59
StationB  2009-05-16 23:59:59 2009-05-16 23:59:59
StationC  2009-05-17 23:59:59 2009-05-17 23:59:59
```

So, the **problem** is for sure in the **camera operation matrix**.

Notice the difference between first part of our reduced camopmatrix (first two deployments of `mica` datapackage:

```r
> cam_op[1:2,1:5]
                              2020-06-19 2020-06-20 2020-06-21 2020-06-22 2020-06-23
B_DL_val 5_beek kleine vijver          0          0          0          0          0
B_DL_val 3_dikke boom                  0          1          1          1          1
```

and the example from camtrapR:

```r
> camop_no_problem[1:3,1:5]
         2009-04-02 2009-04-03 2009-04-04 2009-04-05 2009-04-06
StationA          1          1          1          1          1
StationB         NA          1          1          1          1
StationC         NA         NA          1          1          1
```

**Comment by damianooldoni** [comment]
Replacing 0's with NAs solve this issue!

```r
hist <- camtrapR::detectionHistory(recordTable = record_table,
                 camOp = dplyr::na_if(cam_op, y = 0), # to fast replace 0 with NAs
                 output = "count",
                 stationCol = "Station",
                 speciesCol = "Species",
                 recordDateTimeCol = "DateTimeOriginal",
                 recordDateTimeFormat ="%Y-%m-%d %H:%M:%S",
                 species = "Sus scrofa",
                 occasionLength = 5,
                 day1 = "station",
                 datesAsOccasionNames = FALSE,
                 occasionStartTime = 0,
                 includeEffort = FALSE,
                 timeZone = "UTC",
                 writecsv = FALSE)
hist$detection_history
                              o1 o2
B_DL_val 5_beek kleine vijver  4 NA
B_DL_val 3_dikke boom          1 NA
```

So, the `get_cam_op()` should be improved. From camtrapR documentation:
> Legend: NA: camera(s) not set up, 0: camera(s) not operational, 1 (or higher): number of operational camera(s) or an indicator for whether the station was operational

In camtrap datapackages the deployment start and end datetimes are defined and so NAs should occur out of the intervals defined by `start`-`end` instead of 0s.

**Comment by damianooldoni** [comment]
Based on discussion with @jimcasaer:
- NAs out of deployment start - end date instead of 0s as I found above
- Camera operation matrix MUST contain decimal values for the start day and the end day if time is provided (as it occurs typically), 1 otherwise. Now 0s are returned. This implies also that argument `use_decimal` MUST disappear from `get_cam_op()`.
